//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPK_generator.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class config
    {
        public string my_name { get; set; }
        public string my_address1 { get; set; }
        public string my_address2 { get; set; }
        public int my_nip { get; set; }
        public string my_email { get; set; }
        public string schema_version { get; set; }
        public int form_variant { get; set; }
    }
}
