//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-dokumenty.mf.gov.pl")]
[System.Xml.Serialization.XmlRootAttribute("InitUpload", Namespace="http://e-dokumenty.mf.gov.pl", IsNullable=false)]
public partial class InitUploadType {
    
    private InitUploadTypeDocumentType documentTypeField;
    
    private string versionField;
    
    private InitUploadTypeEncryptionKey encryptionKeyField;
    
    private ArrayOfDocumentType documentListField;
    
    public InitUploadType() {
        this.versionField = "01.02.01.20160617";
    }
    
    /// <remarks/>
    public InitUploadTypeDocumentType DocumentType {
        get {
            return this.documentTypeField;
        }
        set {
            this.documentTypeField = value;
        }
    }
    
    /// <remarks/>
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    public InitUploadTypeEncryptionKey EncryptionKey {
        get {
            return this.encryptionKeyField;
        }
        set {
            this.encryptionKeyField = value;
        }
    }
    
    /// <remarks/>
    public ArrayOfDocumentType DocumentList {
        get {
            return this.documentListField;
        }
        set {
            this.documentListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://e-dokumenty.mf.gov.pl")]
public enum InitUploadTypeDocumentType {
    
    /// <remarks/>
    JPK,
    
    /// <remarks/>
    JPKAH,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://e-dokumenty.mf.gov.pl")]
public partial class InitUploadTypeEncryptionKey : EncryptionKeyRSAType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-dokumenty.mf.gov.pl")]
public partial class EncryptionKeyRSAType {
    
    private string algorithmField;
    
    private string modeField;
    
    private string paddingField;
    
    private string encodingField;
    
    private string valueField;
    
    public EncryptionKeyRSAType() {
        this.algorithmField = "RSA";
        this.modeField = "ECB";
        this.paddingField = "PKCS#1";
        this.encodingField = "Base64";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string algorithm {
        get {
            return this.algorithmField;
        }
        set {
            this.algorithmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mode {
        get {
            return this.modeField;
        }
        set {
            this.modeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string padding {
        get {
            return this.paddingField;
        }
        set {
            this.paddingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string encoding {
        get {
            return this.encodingField;
        }
        set {
            this.encodingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-dokumenty.mf.gov.pl")]
public partial class HashValueMD5Type {
    
    private string algorithmField;
    
    private string encodingField;
    
    private string valueField;
    
    public HashValueMD5Type() {
        this.algorithmField = "MD5";
        this.encodingField = "Base64";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string algorithm {
        get {
            return this.algorithmField;
        }
        set {
            this.algorithmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string encoding {
        get {
            return this.encodingField;
        }
        set {
            this.encodingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-dokumenty.mf.gov.pl")]
public partial class FileSignatureType {
    
    private int ordinalNumberField;
    
    private string fileNameField;
    
    private int contentLengthField;
    
    private FileSignatureTypeHashValue hashValueField;
    
    /// <remarks/>
    public int OrdinalNumber {
        get {
            return this.ordinalNumberField;
        }
        set {
            this.ordinalNumberField = value;
        }
    }
    
    /// <remarks/>
    public string FileName {
        get {
            return this.fileNameField;
        }
        set {
            this.fileNameField = value;
        }
    }
    
    /// <remarks/>
    public int ContentLength {
        get {
            return this.contentLengthField;
        }
        set {
            this.contentLengthField = value;
        }
    }
    
    /// <remarks/>
    public FileSignatureTypeHashValue HashValue {
        get {
            return this.hashValueField;
        }
        set {
            this.hashValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://e-dokumenty.mf.gov.pl")]
public partial class FileSignatureTypeHashValue : HashValueMD5Type {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-dokumenty.mf.gov.pl")]
public partial class EncryptionAESIVType {
    
    private string bytesField;
    
    private string encodingField;
    
    private string valueField;
    
    public EncryptionAESIVType() {
        this.bytesField = "16";
        this.encodingField = "Base64";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string bytes {
        get {
            return this.bytesField;
        }
        set {
            this.bytesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string encoding {
        get {
            return this.encodingField;
        }
        set {
            this.encodingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-dokumenty.mf.gov.pl")]
public partial class ArrayOfFileSignatureType {
    
    private ArrayOfFileSignatureTypePackaging packagingField;
    
    private ArrayOfFileSignatureTypeEncryption encryptionField;
    
    private FileSignatureType[] fileSignatureField;
    
    /// <remarks/>
    public ArrayOfFileSignatureTypePackaging Packaging {
        get {
            return this.packagingField;
        }
        set {
            this.packagingField = value;
        }
    }
    
    /// <remarks/>
    public ArrayOfFileSignatureTypeEncryption Encryption {
        get {
            return this.encryptionField;
        }
        set {
            this.encryptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FileSignature")]
    public FileSignatureType[] FileSignature {
        get {
            return this.fileSignatureField;
        }
        set {
            this.fileSignatureField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://e-dokumenty.mf.gov.pl")]
public partial class ArrayOfFileSignatureTypePackaging {
    
    private ArrayOfFileSignatureTypePackagingSplitZip itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SplitZip")]
    public ArrayOfFileSignatureTypePackagingSplitZip Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://e-dokumenty.mf.gov.pl")]
public partial class ArrayOfFileSignatureTypePackagingSplitZip {
    
    private string typeField;
    
    private string modeField;
    
    public ArrayOfFileSignatureTypePackagingSplitZip() {
        this.typeField = "split";
        this.modeField = "zip";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mode {
        get {
            return this.modeField;
        }
        set {
            this.modeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://e-dokumenty.mf.gov.pl")]
public partial class ArrayOfFileSignatureTypeEncryption {
    
    private ArrayOfFileSignatureTypeEncryptionAES itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AES")]
    public ArrayOfFileSignatureTypeEncryptionAES Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://e-dokumenty.mf.gov.pl")]
public partial class ArrayOfFileSignatureTypeEncryptionAES {
    
    private ArrayOfFileSignatureTypeEncryptionAESIV ivField;
    
    private int sizeField;
    
    private int blockField;
    
    private string modeField;
    
    private string paddingField;
    
    public ArrayOfFileSignatureTypeEncryptionAES() {
        this.sizeField = 256;
        this.blockField = 16;
        this.modeField = "CBC";
        this.paddingField = "PKCS#7";
    }
    
    /// <remarks/>
    public ArrayOfFileSignatureTypeEncryptionAESIV IV {
        get {
            return this.ivField;
        }
        set {
            this.ivField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int size {
        get {
            return this.sizeField;
        }
        set {
            this.sizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int block {
        get {
            return this.blockField;
        }
        set {
            this.blockField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mode {
        get {
            return this.modeField;
        }
        set {
            this.modeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string padding {
        get {
            return this.paddingField;
        }
        set {
            this.paddingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://e-dokumenty.mf.gov.pl")]
public partial class ArrayOfFileSignatureTypeEncryptionAESIV : EncryptionAESIVType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-dokumenty.mf.gov.pl")]
public partial class HashValueSHAType {
    
    private string algorithmField;
    
    private string encodingField;
    
    private string valueField;
    
    public HashValueSHAType() {
        this.algorithmField = "SHA-256";
        this.encodingField = "Base64";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string algorithm {
        get {
            return this.algorithmField;
        }
        set {
            this.algorithmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string encoding {
        get {
            return this.encodingField;
        }
        set {
            this.encodingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-dokumenty.mf.gov.pl")]
public partial class DocumentType {
    
    private DocumentTypeFormCode formCodeField;
    
    private string fileNameField;
    
    private long contentLengthField;
    
    private DocumentTypeHashValue hashValueField;
    
    private DocumentTypeFileSignatureList fileSignatureListField;
    
    /// <remarks/>
    public DocumentTypeFormCode FormCode {
        get {
            return this.formCodeField;
        }
        set {
            this.formCodeField = value;
        }
    }
    
    /// <remarks/>
    public string FileName {
        get {
            return this.fileNameField;
        }
        set {
            this.fileNameField = value;
        }
    }
    
    /// <remarks/>
    public long ContentLength {
        get {
            return this.contentLengthField;
        }
        set {
            this.contentLengthField = value;
        }
    }
    
    /// <remarks/>
    public DocumentTypeHashValue HashValue {
        get {
            return this.hashValueField;
        }
        set {
            this.hashValueField = value;
        }
    }
    
    /// <remarks/>
    public DocumentTypeFileSignatureList FileSignatureList {
        get {
            return this.fileSignatureListField;
        }
        set {
            this.fileSignatureListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://e-dokumenty.mf.gov.pl")]
public partial class DocumentTypeFormCode {
    
    private string systemCodeField;
    
    private string schemaVersionField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string systemCode {
        get {
            return this.systemCodeField;
        }
        set {
            this.systemCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string schemaVersion {
        get {
            return this.schemaVersionField;
        }
        set {
            this.schemaVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://e-dokumenty.mf.gov.pl")]
public partial class DocumentTypeHashValue : HashValueSHAType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://e-dokumenty.mf.gov.pl")]
public partial class DocumentTypeFileSignatureList : ArrayOfFileSignatureType {
    
    private int filesNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int filesNumber {
        get {
            return this.filesNumberField;
        }
        set {
            this.filesNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-dokumenty.mf.gov.pl")]
public partial class ArrayOfDocumentType {
    
    private ArrayOfDocumentTypeDocument documentField;
    
    /// <remarks/>
    public ArrayOfDocumentTypeDocument Document {
        get {
            return this.documentField;
        }
        set {
            this.documentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://e-dokumenty.mf.gov.pl")]
public partial class ArrayOfDocumentTypeDocument : DocumentType {
}
