//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class config
    {
        public int config_id { get; set; }
        public string my_name { get; set; }
        public string my_address { get; set; }
        public string my_nip { get; set; }
        public string my_email { get; set; }
        public string form_variant { get; set; }
        public string path_for_jpk { get; set; }
        public string purpose_of_submission { get; set; }
        public string system_name { get; set; }
    }
}
