// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.1.854 Microsoft Reciprocal License (Ms-RL) 
//    <NameSpace>JPK_generator</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace JPK_generator.XSD
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public enum TKodKraju
    {

        /// <remarks/>
        AF,

        /// <remarks/>
        AX,

        /// <remarks/>
        AL,

        /// <remarks/>
        DZ,

        /// <remarks/>
        AD,

        /// <remarks/>
        AO,

        /// <remarks/>
        AI,

        /// <remarks/>
        AQ,

        /// <remarks/>
        AG,

        /// <remarks/>
        AN,

        /// <remarks/>
        SA,

        /// <remarks/>
        AR,

        /// <remarks/>
        AM,

        /// <remarks/>
        AW,

        /// <remarks/>
        AU,

        /// <remarks/>
        AT,

        /// <remarks/>
        AZ,

        /// <remarks/>
        BS,

        /// <remarks/>
        BH,

        /// <remarks/>
        BD,

        /// <remarks/>
        BB,

        /// <remarks/>
        BE,

        /// <remarks/>
        BZ,

        /// <remarks/>
        BJ,

        /// <remarks/>
        BM,

        /// <remarks/>
        BT,

        /// <remarks/>
        BY,

        /// <remarks/>
        BO,

        /// <remarks/>
        BA,

        /// <remarks/>
        BW,

        /// <remarks/>
        BR,

        /// <remarks/>
        BN,

        /// <remarks/>
        IO,

        /// <remarks/>
        BG,

        /// <remarks/>
        BF,

        /// <remarks/>
        BI,

        /// <remarks/>
        XC,

        /// <remarks/>
        CL,

        /// <remarks/>
        CN,

        /// <remarks/>
        HR,

        /// <remarks/>
        CY,

        /// <remarks/>
        TD,

        /// <remarks/>
        ME,

        /// <remarks/>
        DK,

        /// <remarks/>
        DM,

        /// <remarks/>
        DO,

        /// <remarks/>
        DJ,

        /// <remarks/>
        EG,

        /// <remarks/>
        EC,

        /// <remarks/>
        ER,

        /// <remarks/>
        EE,

        /// <remarks/>
        ET,

        /// <remarks/>
        FK,

        /// <remarks/>
        FJ,

        /// <remarks/>
        PH,

        /// <remarks/>
        FI,

        /// <remarks/>
        FR,

        /// <remarks/>
        TF,

        /// <remarks/>
        GA,

        /// <remarks/>
        GM,

        /// <remarks/>
        GH,

        /// <remarks/>
        GI,

        /// <remarks/>
        GR,

        /// <remarks/>
        GD,

        /// <remarks/>
        GL,

        /// <remarks/>
        GE,

        /// <remarks/>
        GU,

        /// <remarks/>
        GG,

        /// <remarks/>
        GY,

        /// <remarks/>
        GF,

        /// <remarks/>
        GP,

        /// <remarks/>
        GT,

        /// <remarks/>
        GN,

        /// <remarks/>
        GQ,

        /// <remarks/>
        GW,

        /// <remarks/>
        HT,

        /// <remarks/>
        ES,

        /// <remarks/>
        HN,

        /// <remarks/>
        HK,

        /// <remarks/>
        IN,

        /// <remarks/>
        ID,

        /// <remarks/>
        IQ,

        /// <remarks/>
        IR,

        /// <remarks/>
        IE,

        /// <remarks/>
        IS,

        /// <remarks/>
        IL,

        /// <remarks/>
        JM,

        /// <remarks/>
        JP,

        /// <remarks/>
        YE,

        /// <remarks/>
        JE,

        /// <remarks/>
        JO,

        /// <remarks/>
        KY,

        /// <remarks/>
        KH,

        /// <remarks/>
        CM,

        /// <remarks/>
        CA,

        /// <remarks/>
        QA,

        /// <remarks/>
        KZ,

        /// <remarks/>
        KE,

        /// <remarks/>
        KG,

        /// <remarks/>
        KI,

        /// <remarks/>
        CO,

        /// <remarks/>
        KM,

        /// <remarks/>
        CG,

        /// <remarks/>
        CD,

        /// <remarks/>
        KP,

        /// <remarks/>
        XK,

        /// <remarks/>
        CR,

        /// <remarks/>
        CU,

        /// <remarks/>
        KW,

        /// <remarks/>
        LA,

        /// <remarks/>
        LS,

        /// <remarks/>
        LB,

        /// <remarks/>
        LR,

        /// <remarks/>
        LY,

        /// <remarks/>
        LI,

        /// <remarks/>
        LT,

        /// <remarks/>
        LV,

        /// <remarks/>
        LU,

        /// <remarks/>
        MK,

        /// <remarks/>
        MG,

        /// <remarks/>
        YT,

        /// <remarks/>
        MO,

        /// <remarks/>
        MW,

        /// <remarks/>
        MV,

        /// <remarks/>
        MY,

        /// <remarks/>
        ML,

        /// <remarks/>
        MT,

        /// <remarks/>
        MP,

        /// <remarks/>
        MA,

        /// <remarks/>
        MQ,

        /// <remarks/>
        MR,

        /// <remarks/>
        MU,

        /// <remarks/>
        MX,

        /// <remarks/>
        XL,

        /// <remarks/>
        FM,

        /// <remarks/>
        UM,

        /// <remarks/>
        MD,

        /// <remarks/>
        MC,

        /// <remarks/>
        MN,

        /// <remarks/>
        MS,

        /// <remarks/>
        MZ,

        /// <remarks/>
        MM,

        /// <remarks/>
        NA,

        /// <remarks/>
        NR,

        /// <remarks/>
        NP,

        /// <remarks/>
        NL,

        /// <remarks/>
        DE,

        /// <remarks/>
        NE,

        /// <remarks/>
        NG,

        /// <remarks/>
        NI,

        /// <remarks/>
        NU,

        /// <remarks/>
        NF,

        /// <remarks/>
        NO,

        /// <remarks/>
        NC,

        /// <remarks/>
        NZ,

        /// <remarks/>
        PS,

        /// <remarks/>
        OM,

        /// <remarks/>
        PK,

        /// <remarks/>
        PW,

        /// <remarks/>
        PA,

        /// <remarks/>
        PG,

        /// <remarks/>
        PY,

        /// <remarks/>
        PE,

        /// <remarks/>
        PN,

        /// <remarks/>
        PF,

        /// <remarks/>
        PL,

        /// <remarks/>
        GS,

        /// <remarks/>
        PT,

        /// <remarks/>
        PR,

        /// <remarks/>
        CF,

        /// <remarks/>
        CZ,

        /// <remarks/>
        KR,

        /// <remarks/>
        ZA,

        /// <remarks/>
        RE,

        /// <remarks/>
        RU,

        /// <remarks/>
        RO,

        /// <remarks/>
        RW,

        /// <remarks/>
        EH,

        /// <remarks/>
        BL,

        /// <remarks/>
        KN,

        /// <remarks/>
        LC,

        /// <remarks/>
        MF,

        /// <remarks/>
        VC,

        /// <remarks/>
        SV,

        /// <remarks/>
        WS,

        /// <remarks/>
        AS,

        /// <remarks/>
        SM,

        /// <remarks/>
        SN,

        /// <remarks/>
        RS,

        /// <remarks/>
        SC,

        /// <remarks/>
        SL,

        /// <remarks/>
        SG,

        /// <remarks/>
        SK,

        /// <remarks/>
        SI,

        /// <remarks/>
        SO,

        /// <remarks/>
        LK,

        /// <remarks/>
        PM,

        /// <remarks/>
        US,

        /// <remarks/>
        SZ,

        /// <remarks/>
        SD,

        /// <remarks/>
        SR,

        /// <remarks/>
        SJ,

        /// <remarks/>
        SH,

        /// <remarks/>
        SY,

        /// <remarks/>
        CH,

        /// <remarks/>
        SE,

        /// <remarks/>
        TJ,

        /// <remarks/>
        TH,

        /// <remarks/>
        TW,

        /// <remarks/>
        TZ,

        /// <remarks/>
        TG,

        /// <remarks/>
        TK,

        /// <remarks/>
        TO,

        /// <remarks/>
        TT,

        /// <remarks/>
        TN,

        /// <remarks/>
        TR,

        /// <remarks/>
        TM,

        /// <remarks/>
        TV,

        /// <remarks/>
        UG,

        /// <remarks/>
        UA,

        /// <remarks/>
        UY,

        /// <remarks/>
        UZ,

        /// <remarks/>
        VU,

        /// <remarks/>
        WF,

        /// <remarks/>
        VA,

        /// <remarks/>
        HU,

        /// <remarks/>
        VE,

        /// <remarks/>
        GB,

        /// <remarks/>
        VN,

        /// <remarks/>
        IT,

        /// <remarks/>
        TL,

        /// <remarks/>
        CI,

        /// <remarks/>
        BV,

        /// <remarks/>
        CX,

        /// <remarks/>
        IM,

        /// <remarks/>
        CK,

        /// <remarks/>
        VI,

        /// <remarks/>
        VG,

        /// <remarks/>
        HM,

        /// <remarks/>
        CC,

        /// <remarks/>
        MH,

        /// <remarks/>
        FO,

        /// <remarks/>
        SB,

        /// <remarks/>
        ST,

        /// <remarks/>
        TC,

        /// <remarks/>
        ZM,

        /// <remarks/>
        CV,

        /// <remarks/>
        ZW,

        /// <remarks/>
        AE,
    }
}
