// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.1.854 Microsoft Reciprocal License (Ms-RL) 
//    <NameSpace>JPK_generator</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace JPK_generator.XSD
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public enum TKodNaczUS
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0202 - NACZELNIK URZĘDU SKARBOWEGO W BOLESŁAWCU")]
        Item0202NACZELNIKURZĘDUSKARBOWEGOWBOLESŁAWCU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0203 - NACZELNIK URZĘDU SKARBOWEGO W BYSTRZYCY KŁODZKIEJ")]
        Item0203NACZELNIKURZĘDUSKARBOWEGOWBYSTRZYCYKŁODZKIEJ,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0204 - NACZELNIK URZĘDU SKARBOWEGO W DZIERŻONIOWIE")]
        Item0204NACZELNIKURZĘDUSKARBOWEGOWDZIERŻONIOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0205 - NACZELNIK URZĘDU SKARBOWEGO W GŁOGOWIE")]
        Item0205NACZELNIKURZĘDUSKARBOWEGOWGŁOGOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0206 - NACZELNIK URZĘDU SKARBOWEGO W JAWORZE")]
        Item0206NACZELNIKURZĘDUSKARBOWEGOWJAWORZE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0207 - NACZELNIK URZĘDU SKARBOWEGO W JELENIEJ GÓRZE")]
        Item0207NACZELNIKURZĘDUSKARBOWEGOWJELENIEJGÓRZE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0208 - NACZELNIK URZĘDU SKARBOWEGO W KAMIENNEJ GÓRZE")]
        Item0208NACZELNIKURZĘDUSKARBOWEGOWKAMIENNEJGÓRZE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0209 - NACZELNIK URZĘDU SKARBOWEGO W KŁODZKU")]
        Item0209NACZELNIKURZĘDUSKARBOWEGOWKŁODZKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0210 - NACZELNIK URZĘDU SKARBOWEGO W LEGNICY")]
        Item0210NACZELNIKURZĘDUSKARBOWEGOWLEGNICY,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0211 - NACZELNIK URZĘDU SKARBOWEGO W LUBANIU")]
        Item0211NACZELNIKURZĘDUSKARBOWEGOWLUBANIU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0212 - NACZELNIK URZĘDU SKARBOWEGO W LUBINIE")]
        Item0212NACZELNIKURZĘDUSKARBOWEGOWLUBINIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0213 - NACZELNIK URZĘDU SKARBOWEGO W LWÓWKU ŚLĄSKIM")]
        Item0213NACZELNIKURZĘDUSKARBOWEGOWLWÓWKUŚLĄSKIM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0214 - NACZELNIK URZĘDU SKARBOWEGO W MILICZU")]
        Item0214NACZELNIKURZĘDUSKARBOWEGOWMILICZU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0215 - NACZELNIK URZĘDU SKARBOWEGO W NOWEJ RUDZIE")]
        Item0215NACZELNIKURZĘDUSKARBOWEGOWNOWEJRUDZIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0216 - NACZELNIK URZĘDU SKARBOWEGO W OLEŚNICY")]
        Item0216NACZELNIKURZĘDUSKARBOWEGOWOLEŚNICY,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0217 - NACZELNIK URZĘDU SKARBOWEGO W OŁAWIE")]
        Item0217NACZELNIKURZĘDUSKARBOWEGOWOŁAWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0218 - NACZELNIK URZĘDU SKARBOWEGO W STRZELINIE")]
        Item0218NACZELNIKURZĘDUSKARBOWEGOWSTRZELINIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0219 - NACZELNIK URZĘDU SKARBOWEGO W ŚRODZIE ŚLĄSKIEJ")]
        Item0219NACZELNIKURZĘDUSKARBOWEGOWŚRODZIEŚLĄSKIEJ,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0220 - NACZELNIK URZĘDU SKARBOWEGO W ŚWIDNICY")]
        Item0220NACZELNIKURZĘDUSKARBOWEGOWŚWIDNICY,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0221 - NACZELNIK URZĘDU SKARBOWEGO W TRZEBNICY")]
        Item0221NACZELNIKURZĘDUSKARBOWEGOWTRZEBNICY,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0222 - NACZELNIK URZĘDU SKARBOWEGO W WAŁBRZYCHU")]
        Item0222NACZELNIKURZĘDUSKARBOWEGOWWAŁBRZYCHU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0223 - NACZELNIK URZĘDU SKARBOWEGO W WOŁOWIE")]
        Item0223NACZELNIKURZĘDUSKARBOWEGOWWOŁOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0224 - NACZELNIK URZĘDU SKARBOWEGO WROCŁAW-FABRYCZNA")]
        Item0224NACZELNIKURZĘDUSKARBOWEGOWROCŁAWFABRYCZNA,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0225 - NACZELNIK URZĘDU SKARBOWEGO WROCŁAW-KRZYKI")]
        Item0225NACZELNIKURZĘDUSKARBOWEGOWROCŁAWKRZYKI,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0226 - NACZELNIK URZĘDU SKARBOWEGO WROCŁAW-PSIE POLE")]
        Item0226NACZELNIKURZĘDUSKARBOWEGOWROCŁAWPSIEPOLE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0227 - NACZELNIK URZĘDU SKARBOWEGO WROCŁAW-STARE MIASTO")]
        Item0227NACZELNIKURZĘDUSKARBOWEGOWROCŁAWSTAREMIASTO,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0228 - NACZELNIK URZĘDU SKARBOWEGO WROCŁAW-ŚRÓDMIEŚCIE")]
        Item0228NACZELNIKURZĘDUSKARBOWEGOWROCŁAWŚRÓDMIEŚCIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0229 - NACZELNIK PIERWSZEGO URZĘDU SKARBOWEGO WE WROCŁAWIU")]
        Item0229NACZELNIKPIERWSZEGOURZĘDUSKARBOWEGOWEWROCŁAWIU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0230 - NACZELNIK URZĘDU SKARBOWEGO W ZĄBKOWICACH ŚLĄSKICH")]
        Item0230NACZELNIKURZĘDUSKARBOWEGOWZĄBKOWICACHŚLĄSKICH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0231 - NACZELNIK URZĘDU SKARBOWEGO W ZGORZELCU")]
        Item0231NACZELNIKURZĘDUSKARBOWEGOWZGORZELCU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0232 - NACZELNIK URZĘDU SKARBOWEGO W ZŁOTORYI")]
        Item0232NACZELNIKURZĘDUSKARBOWEGOWZŁOTORYI,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0233 - NACZELNIK URZĘDU SKARBOWEGO W GÓRZE")]
        Item0233NACZELNIKURZĘDUSKARBOWEGOWGÓRZE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0234 - NACZELNIK URZĘDU SKARBOWEGO W POLKOWICACH")]
        Item0234NACZELNIKURZĘDUSKARBOWEGOWPOLKOWICACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0271 - NACZELNIK DOLNOŚLĄSKIEGO URZĘDU SKARBOWEGO WE WROCŁAWIU")]
        Item0271NACZELNIKDOLNOŚLĄSKIEGOURZĘDUSKARBOWEGOWEWROCŁAWIU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0402 - NACZELNIK URZĘDU SKARBOWEGO W ALEKSANDROWIE KUJAWSKIM")]
        Item0402NACZELNIKURZĘDUSKARBOWEGOWALEKSANDROWIEKUJAWSKIM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0403 - NACZELNIK URZĘDU SKARBOWEGO W BRODNICY")]
        Item0403NACZELNIKURZĘDUSKARBOWEGOWBRODNICY,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0404 - NACZELNIK PIERWSZEGO URZĘDU SKARBOWEGO W BYDGOSZCZY")]
        Item0404NACZELNIKPIERWSZEGOURZĘDUSKARBOWEGOWBYDGOSZCZY,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0405 - NACZELNIK DRUGIEGO URZĘDU SKARBOWEGO W BYDGOSZCZY")]
        Item0405NACZELNIKDRUGIEGOURZĘDUSKARBOWEGOWBYDGOSZCZY,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0406 - NACZELNIK TRZECIEGO URZĘDU SKARBOWEGO W BYDGOSZCZY")]
        Item0406NACZELNIKTRZECIEGOURZĘDUSKARBOWEGOWBYDGOSZCZY,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0407 - NACZELNIK URZĘDU SKARBOWEGO W CHEŁMNIE")]
        Item0407NACZELNIKURZĘDUSKARBOWEGOWCHEŁMNIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0408 - NACZELNIK URZĘDU SKARBOWEGO W GRUDZIĄDZU")]
        Item0408NACZELNIKURZĘDUSKARBOWEGOWGRUDZIĄDZU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0409 - NACZELNIK URZĘDU SKARBOWEGO W INOWROCŁAWIU")]
        Item0409NACZELNIKURZĘDUSKARBOWEGOWINOWROCŁAWIU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0410 - NACZELNIK URZĘDU SKARBOWEGO W LIPNIE")]
        Item0410NACZELNIKURZĘDUSKARBOWEGOWLIPNIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0411 - NACZELNIK URZĘDU SKARBOWEGO W MOGILNIE")]
        Item0411NACZELNIKURZĘDUSKARBOWEGOWMOGILNIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0412 - NACZELNIK URZĘDU SKARBOWEGO W NAKLE NAD NOTECIĄ")]
        Item0412NACZELNIKURZĘDUSKARBOWEGOWNAKLENADNOTECIĄ,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0413 - NACZELNIK URZĘDU SKARBOWEGO W RADZIEJOWIE")]
        Item0413NACZELNIKURZĘDUSKARBOWEGOWRADZIEJOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0414 - NACZELNIK URZĘDU SKARBOWEGO W RYPINIE")]
        Item0414NACZELNIKURZĘDUSKARBOWEGOWRYPINIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0415 - NACZELNIK URZĘDU SKARBOWEGO W ŚWIECIU")]
        Item0415NACZELNIKURZĘDUSKARBOWEGOWŚWIECIU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0416 - NACZELNIK PIERWSZEGO URZĘDU SKARBOWEGO W TORUNIU")]
        Item0416NACZELNIKPIERWSZEGOURZĘDUSKARBOWEGOWTORUNIU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0417 - NACZELNIK DRUGIEGO URZĘDU SKARBOWEGO W TORUNIU")]
        Item0417NACZELNIKDRUGIEGOURZĘDUSKARBOWEGOWTORUNIU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0418 - NACZELNIK URZĘDU SKARBOWEGO W TUCHOLI")]
        Item0418NACZELNIKURZĘDUSKARBOWEGOWTUCHOLI,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0419 - NACZELNIK URZĘDU SKARBOWEGO W WĄBRZEŹNIE")]
        Item0419NACZELNIKURZĘDUSKARBOWEGOWWĄBRZEŹNIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0420 - NACZELNIK URZĘDU SKARBOWEGO WE WŁOCŁAWKU")]
        Item0420NACZELNIKURZĘDUSKARBOWEGOWEWŁOCŁAWKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0421 - NACZELNIK URZĘDU SKARBOWEGO W ŻNINIE")]
        Item0421NACZELNIKURZĘDUSKARBOWEGOWŻNINIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0422 - NACZELNIK URZĘDU SKARBOWEGO W GOLUBIU-DOBRZYNIU")]
        Item0422NACZELNIKURZĘDUSKARBOWEGOWGOLUBIUDOBRZYNIU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0423 - NACZELNIK URZĘDU SKARBOWEGO W SEPÓLNIE KRAJEŃSKIM")]
        Item0423NACZELNIKURZĘDUSKARBOWEGOWSEPÓLNIEKRAJEŃSKIM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0471 - NACZELNIK KUJAWSKO-POMORSKIEGO URZĘDU SKARBOWEGO W BYDGOSZCZY")]
        Item0471NACZELNIKKUJAWSKOPOMORSKIEGOURZĘDUSKARBOWEGOWBYDGOSZCZY,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0602 - NACZELNIK URZĘDU SKARBOWEGO W BIAŁEJ PODLASKIEJ")]
        Item0602NACZELNIKURZĘDUSKARBOWEGOWBIAŁEJPODLASKIEJ,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0603 - NACZELNIK URZĘDU SKARBOWEGO W BIŁGORAJU")]
        Item0603NACZELNIKURZĘDUSKARBOWEGOWBIŁGORAJU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0604 - NACZELNIK URZĘDU SKARBOWEGO W CHEŁMIE")]
        Item0604NACZELNIKURZĘDUSKARBOWEGOWCHEŁMIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0605 - NACZELNIK URZĘDU SKARBOWEGO W HRUBIESZOWIE")]
        Item0605NACZELNIKURZĘDUSKARBOWEGOWHRUBIESZOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0606 - NACZELNIK URZĘDU SKARBOWEGO W JANOWIE LUBELSKIM")]
        Item0606NACZELNIKURZĘDUSKARBOWEGOWJANOWIELUBELSKIM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0607 - NACZELNIK URZĘDU SKARBOWEGO W KRASNYMSTAWIE")]
        Item0607NACZELNIKURZĘDUSKARBOWEGOWKRASNYMSTAWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0608 - NACZELNIK URZĘDU SKARBOWEGO W KRAŚNIKU")]
        Item0608NACZELNIKURZĘDUSKARBOWEGOWKRAŚNIKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0609 - NACZELNIK URZĘDU SKARBOWEGO W LUBARTOWIE")]
        Item0609NACZELNIKURZĘDUSKARBOWEGOWLUBARTOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0610 - NACZELNIK PIERWSZEGO URZĘDU SKARBOWEGO W LUBLINIE")]
        Item0610NACZELNIKPIERWSZEGOURZĘDUSKARBOWEGOWLUBLINIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0611 - NACZELNIK DRUGIEGO URZĘDU SKARBOWEGO W LUBLINIE")]
        Item0611NACZELNIKDRUGIEGOURZĘDUSKARBOWEGOWLUBLINIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0612 - NACZELNIK TRZECIEGO URZĘDU SKARBOWEGO W LUBLINIE")]
        Item0612NACZELNIKTRZECIEGOURZĘDUSKARBOWEGOWLUBLINIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0613 - NACZELNIK URZĘDU SKARBOWEGO W ŁUKOWIE")]
        Item0613NACZELNIKURZĘDUSKARBOWEGOWŁUKOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0614 - NACZELNIK URZĘDU SKARBOWEGO W OPOLU LUBELSKIM")]
        Item0614NACZELNIKURZĘDUSKARBOWEGOWOPOLULUBELSKIM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0615 - NACZELNIK URZĘDU SKARBOWEGO W PARCZEWIE")]
        Item0615NACZELNIKURZĘDUSKARBOWEGOWPARCZEWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0616 - NACZELNIK URZĘDU SKARBOWEGO W PUŁAWACH")]
        Item0616NACZELNIKURZĘDUSKARBOWEGOWPUŁAWACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0617 - NACZELNIK URZĘDU SKARBOWEGO W RADZYNIU PODLASKIM")]
        Item0617NACZELNIKURZĘDUSKARBOWEGOWRADZYNIUPODLASKIM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0618 - NACZELNIK URZĘDU SKARBOWEGO W TOMASZOWIE LUBELSKIM")]
        Item0618NACZELNIKURZĘDUSKARBOWEGOWTOMASZOWIELUBELSKIM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0619 - NACZELNIK URZĘDU SKARBOWEGO WE WŁODAWIE")]
        Item0619NACZELNIKURZĘDUSKARBOWEGOWEWŁODAWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0620 - NACZELNIK URZĘDU SKARBOWEGO W ZAMOŚCIU")]
        Item0620NACZELNIKURZĘDUSKARBOWEGOWZAMOŚCIU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0621 - NACZELNIK URZĘDU SKARBOWEGO W ŁĘCZNEJ")]
        Item0621NACZELNIKURZĘDUSKARBOWEGOWŁĘCZNEJ,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0622 - NACZELNIK URZĘDU SKARBOWEGO W RYKACH")]
        Item0622NACZELNIKURZĘDUSKARBOWEGOWRYKACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0671 - NACZELNIK LUBELSKIEGO URZĘDU SKARBOWEGO W LUBLINIE")]
        Item0671NACZELNIKLUBELSKIEGOURZĘDUSKARBOWEGOWLUBLINIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0802 - NACZELNIK URZĘDU SKARBOWEGO W GORZOWIE WIELKOPOLSKIM")]
        Item0802NACZELNIKURZĘDUSKARBOWEGOWGORZOWIEWIELKOPOLSKIM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0803 - NACZELNIK URZĘDU SKARBOWEGO W KROŚNIE ODRZAŃSKIM")]
        Item0803NACZELNIKURZĘDUSKARBOWEGOWKROŚNIEODRZAŃSKIM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0804 - NACZELNIK URZĘDU SKARBOWEGO W MIĘDZYRZECZU")]
        Item0804NACZELNIKURZĘDUSKARBOWEGOWMIĘDZYRZECZU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0805 - NACZELNIK URZĘDU SKARBOWEGO W NOWEJ SOLI")]
        Item0805NACZELNIKURZĘDUSKARBOWEGOWNOWEJSOLI,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0806 - NACZELNIK URZĘDU SKARBOWEGO W SŁUBICACH")]
        Item0806NACZELNIKURZĘDUSKARBOWEGOWSŁUBICACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0807 - NACZELNIK URZĘDU SKARBOWEGO W ŚWIEBODZINIE")]
        Item0807NACZELNIKURZĘDUSKARBOWEGOWŚWIEBODZINIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0808 - NACZELNIK PIERWSZEGO URZĘDU SKARBOWEGO W ZIELONEJ GÓRZE")]
        Item0808NACZELNIKPIERWSZEGOURZĘDUSKARBOWEGOWZIELONEJGÓRZE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0809 - NACZELNIK DRUGIEGO URZĘDU SKARBOWEGO W ZIELONEJ GÓRZE")]
        Item0809NACZELNIKDRUGIEGOURZĘDUSKARBOWEGOWZIELONEJGÓRZE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0810 - NACZELNIK URZĘDU SKARBOWEGO W ŻAGANIU")]
        Item0810NACZELNIKURZĘDUSKARBOWEGOWŻAGANIU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0811 - NACZELNIK URZĘDU SKARBOWEGO W ŻARACH")]
        Item0811NACZELNIKURZĘDUSKARBOWEGOWŻARACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0812 - NACZELNIK URZĘDU SKARBOWEGO W DREZDENKU")]
        Item0812NACZELNIKURZĘDUSKARBOWEGOWDREZDENKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0813 - NACZELNIK URZĘDU SKARBOWEGO W SULĘCINIE")]
        Item0813NACZELNIKURZĘDUSKARBOWEGOWSULĘCINIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0814 - NACZELNIK URZĘDU SKARBOWEGO WE WSCHOWIE")]
        Item0814NACZELNIKURZĘDUSKARBOWEGOWEWSCHOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0871 - NACZELNIK LUBUSKIEGO URZĘDU SKARBOWEGO W ZIELONEJ GÓRZE")]
        Item0871NACZELNIKLUBUSKIEGOURZĘDUSKARBOWEGOWZIELONEJGÓRZE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1002 - NACZELNIK URZĘDU SKARBOWEGO W BEŁCHATOWIE")]
        Item1002NACZELNIKURZĘDUSKARBOWEGOWBEŁCHATOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1003 - NACZELNIK URZĘDU SKARBOWEGO W BRZEZINACH")]
        Item1003NACZELNIKURZĘDUSKARBOWEGOWBRZEZINACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1004 - NACZELNIK URZĘDU SKARBOWEGO W GŁOWNIE")]
        Item1004NACZELNIKURZĘDUSKARBOWEGOWGŁOWNIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1005 - NACZELNIK URZĘDU SKARBOWEGO W KUTNIE")]
        Item1005NACZELNIKURZĘDUSKARBOWEGOWKUTNIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1006 - NACZELNIK URZĘDU SKARBOWEGO W ŁASKU")]
        Item1006NACZELNIKURZĘDUSKARBOWEGOWŁASKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1007 - NACZELNIK URZĘDU SKARBOWEGO W ŁOWICZU")]
        Item1007NACZELNIKURZĘDUSKARBOWEGOWŁOWICZU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1008 - NACZELNIK PIERWSZEGO URZĘDU SKARBOWEGO ŁÓDŹ-BAŁUTY")]
        Item1008NACZELNIKPIERWSZEGOURZĘDUSKARBOWEGOŁÓDŹBAŁUTY,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1009 - NACZELNIK DRUGIEGO URZĘDU SKARBOWEGO ŁÓDŹ-BAŁUTY")]
        Item1009NACZELNIKDRUGIEGOURZĘDUSKARBOWEGOŁÓDŹBAŁUTY,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1010 - NACZELNIK PIERWSZEGO URZĘDU SKARBOWEGO ŁÓDŹ-GÓRNA")]
        Item1010NACZELNIKPIERWSZEGOURZĘDUSKARBOWEGOŁÓDŹGÓRNA,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1011 - NACZELNIK DRUGIEGO URZĘDU SKARBOWEGO ŁÓDŹ-GÓRNA")]
        Item1011NACZELNIKDRUGIEGOURZĘDUSKARBOWEGOŁÓDŹGÓRNA,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1012 - NACZELNIK URZĘDU SKARBOWEGO ŁÓDŹ-POLESIE")]
        Item1012NACZELNIKURZĘDUSKARBOWEGOŁÓDŹPOLESIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1013 - NACZELNIK URZĘDU SKARBOWEGO ŁÓDŹ-ŚRÓDMIEŚCIE")]
        Item1013NACZELNIKURZĘDUSKARBOWEGOŁÓDŹŚRÓDMIEŚCIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1014 - NACZELNIK URZĘDU SKARBOWEGO ŁÓDŹ-WIDZEW")]
        Item1014NACZELNIKURZĘDUSKARBOWEGOŁÓDŹWIDZEW,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1015 - NACZELNIK URZĘDU SKARBOWEGO W OPOCZNIE")]
        Item1015NACZELNIKURZĘDUSKARBOWEGOWOPOCZNIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1016 - NACZELNIK URZĘDU SKARBOWEGO W PABIANICACH")]
        Item1016NACZELNIKURZĘDUSKARBOWEGOWPABIANICACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1017 - NACZELNIK URZĘDU SKARBOWEGO W PIOTRKOWIE TRYBUNALSKIM")]
        Item1017NACZELNIKURZĘDUSKARBOWEGOWPIOTRKOWIETRYBUNALSKIM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1018 - NACZELNIK URZĘDU SKARBOWEGO W PODDĘBICACH")]
        Item1018NACZELNIKURZĘDUSKARBOWEGOWPODDĘBICACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1019 - NACZELNIK URZĘDU SKARBOWEGO W RADOMSKU")]
        Item1019NACZELNIKURZĘDUSKARBOWEGOWRADOMSKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1020 - NACZELNIK URZĘDU SKARBOWEGO W RAWIE MAZOWIECKIEJ")]
        Item1020NACZELNIKURZĘDUSKARBOWEGOWRAWIEMAZOWIECKIEJ,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1021 - NACZELNIK URZĘDU SKARBOWEGO W SIERADZU")]
        Item1021NACZELNIKURZĘDUSKARBOWEGOWSIERADZU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1022 - NACZELNIK URZĘDU SKARBOWEGO W SKIERNIEWICACH")]
        Item1022NACZELNIKURZĘDUSKARBOWEGOWSKIERNIEWICACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1023 - NACZELNIK URZĘDU SKARBOWEGO W TOMASZOWIE MAZOWIECKIM")]
        Item1023NACZELNIKURZĘDUSKARBOWEGOWTOMASZOWIEMAZOWIECKIM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1024 - NACZELNIK URZĘDU SKARBOWEGO W WIELUNIU")]
        Item1024NACZELNIKURZĘDUSKARBOWEGOWWIELUNIU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1025 - NACZELNIK URZĘDU SKARBOWEGO W ZDUŃSKIEJ WOLI")]
        Item1025NACZELNIKURZĘDUSKARBOWEGOWZDUŃSKIEJWOLI,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1026 - NACZELNIK URZĘDU SKARBOWEGO W ZGIERZU")]
        Item1026NACZELNIKURZĘDUSKARBOWEGOWZGIERZU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1027 - NACZELNIK URZĘDU SKARBOWEGO W WIERUSZOWIE")]
        Item1027NACZELNIKURZĘDUSKARBOWEGOWWIERUSZOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1028 - NACZELNIK URZĘDU SKARBOWEGO W ŁĘCZYCY")]
        Item1028NACZELNIKURZĘDUSKARBOWEGOWŁĘCZYCY,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1029 - NACZELNIK URZĘDU SKARBOWEGO W PAJĘCZNIE")]
        Item1029NACZELNIKURZĘDUSKARBOWEGOWPAJĘCZNIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1071 - NACZELNIK ŁÓDZKIEGO URZĘDU SKARBOWEGO W ŁODZI")]
        Item1071NACZELNIKŁÓDZKIEGOURZĘDUSKARBOWEGOWŁODZI,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1202 - NACZELNIK URZĘDU SKARBOWEGO W BOCHNI")]
        Item1202NACZELNIKURZĘDUSKARBOWEGOWBOCHNI,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1203 - NACZELNIK URZĘDU SKARBOWEGO W BRZESKU")]
        Item1203NACZELNIKURZĘDUSKARBOWEGOWBRZESKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1204 - NACZELNIK URZĘDU SKARBOWEGO W CHRZANOWIE")]
        Item1204NACZELNIKURZĘDUSKARBOWEGOWCHRZANOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1205 - NACZELNIK URZĘDU SKARBOWEGO W DĄBROWIE TARNOWSKIEJ")]
        Item1205NACZELNIKURZĘDUSKARBOWEGOWDĄBROWIETARNOWSKIEJ,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1206 - NACZELNIK URZĘDU SKARBOWEGO W GORLICACH")]
        Item1206NACZELNIKURZĘDUSKARBOWEGOWGORLICACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1207 - NACZELNIK PIERWSZEGO URZĘDU SKARBOWEGO KRAKÓW")]
        Item1207NACZELNIKPIERWSZEGOURZĘDUSKARBOWEGOKRAKÓW,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1208 - NACZELNIK URZĘDU SKARBOWEGO KRAKÓW-KROWODRZA")]
        Item1208NACZELNIKURZĘDUSKARBOWEGOKRAKÓWKROWODRZA,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1209 - NACZELNIK URZĘDU SKARBOWEGO KRAKÓW-NOWA HUTA")]
        Item1209NACZELNIKURZĘDUSKARBOWEGOKRAKÓWNOWAHUTA,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1210 - NACZELNIK URZĘDU SKARBOWEGO KRAKÓW-PODGÓRZE")]
        Item1210NACZELNIKURZĘDUSKARBOWEGOKRAKÓWPODGÓRZE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1211 - NACZELNIK URZĘDU SKARBOWEGO KRAKÓW-PRĄDNIK")]
        Item1211NACZELNIKURZĘDUSKARBOWEGOKRAKÓWPRĄDNIK,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1212 - NACZELNIK URZĘDU SKARBOWEGO KRAKÓW-STARE MIASTO")]
        Item1212NACZELNIKURZĘDUSKARBOWEGOKRAKÓWSTAREMIASTO,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1213 - NACZELNIK URZĘDU SKARBOWEGO KRAKÓW-ŚRÓDMIEŚCIE")]
        Item1213NACZELNIKURZĘDUSKARBOWEGOKRAKÓWŚRÓDMIEŚCIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1214 - NACZELNIK URZĘDU SKARBOWEGO W LIMANOWEJ")]
        Item1214NACZELNIKURZĘDUSKARBOWEGOWLIMANOWEJ,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1215 - NACZELNIK URZĘDU SKARBOWEGO W MIECHOWIE")]
        Item1215NACZELNIKURZĘDUSKARBOWEGOWMIECHOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1216 - NACZELNIK URZĘDU SKARBOWEGO W MYŚLENICACH")]
        Item1216NACZELNIKURZĘDUSKARBOWEGOWMYŚLENICACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1217 - NACZELNIK URZĘDU SKARBOWEGO W NOWYM SĄCZU")]
        Item1217NACZELNIKURZĘDUSKARBOWEGOWNOWYMSĄCZU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1218 - NACZELNIK URZĘDU SKARBOWEGO W NOWYM TARGU")]
        Item1218NACZELNIKURZĘDUSKARBOWEGOWNOWYMTARGU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1219 - NACZELNIK URZĘDU SKARBOWEGO W OLKUSZU")]
        Item1219NACZELNIKURZĘDUSKARBOWEGOWOLKUSZU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1220 - NACZELNIK URZĘDU SKARBOWEGO W OŚWIĘCIMIU")]
        Item1220NACZELNIKURZĘDUSKARBOWEGOWOŚWIĘCIMIU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1221 - NACZELNIK URZĘDU SKARBOWEGO W PROSZOWICACH")]
        Item1221NACZELNIKURZĘDUSKARBOWEGOWPROSZOWICACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1222 - NACZELNIK URZĘDU SKARBOWEGO W SUCHEJ BESKIDZKIEJ")]
        Item1222NACZELNIKURZĘDUSKARBOWEGOWSUCHEJBESKIDZKIEJ,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1223 - NACZELNIK PIERWSZEGO URZĘDU SKARBOWEGO W TARNOWIE")]
        Item1223NACZELNIKPIERWSZEGOURZĘDUSKARBOWEGOWTARNOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1224 - NACZELNIK DRUGIEGO URZĘDU SKARBOWEGO W TARNOWIE")]
        Item1224NACZELNIKDRUGIEGOURZĘDUSKARBOWEGOWTARNOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1225 - NACZELNIK URZĘDU SKARBOWEGO W WADOWICACH")]
        Item1225NACZELNIKURZĘDUSKARBOWEGOWWADOWICACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1226 - NACZELNIK URZĘDU SKARBOWEGO W WIELICZCE")]
        Item1226NACZELNIKURZĘDUSKARBOWEGOWWIELICZCE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1227 - NACZELNIK URZĘDU SKARBOWEGO W ZAKOPANEM")]
        Item1227NACZELNIKURZĘDUSKARBOWEGOWZAKOPANEM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1228 - NACZELNIK DRUGIEGO URZĘDU SKARBOWEGO KRAKÓW")]
        Item1228NACZELNIKDRUGIEGOURZĘDUSKARBOWEGOKRAKÓW,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1271 - NACZELNIK MAŁOPOLSKIEGO URZĘDU SKARBOWEGO W KRAKOWIE")]
        Item1271NACZELNIKMAŁOPOLSKIEGOURZĘDUSKARBOWEGOWKRAKOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1402 - NACZELNIK URZĘDU SKARBOWEGO W BIAŁOBRZEGACH")]
        Item1402NACZELNIKURZĘDUSKARBOWEGOWBIAŁOBRZEGACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1403 - NACZELNIK URZĘDU SKARBOWEGO W CIECHANOWIE")]
        Item1403NACZELNIKURZĘDUSKARBOWEGOWCIECHANOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1404 - NACZELNIK URZĘDU SKARBOWEGO W GARWOLINIE")]
        Item1404NACZELNIKURZĘDUSKARBOWEGOWGARWOLINIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1405 - NACZELNIK URZĘDU SKARBOWEGO W GOSTYNINIE")]
        Item1405NACZELNIKURZĘDUSKARBOWEGOWGOSTYNINIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1406 - NACZELNIK URZĘDU SKARBOWEGO W GRODZISKU MAZOWIECKIM")]
        Item1406NACZELNIKURZĘDUSKARBOWEGOWGRODZISKUMAZOWIECKIM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1407 - NACZELNIK URZĘDU SKARBOWEGO W GRÓJCU")]
        Item1407NACZELNIKURZĘDUSKARBOWEGOWGRÓJCU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1408 - NACZELNIK URZĘDU SKARBOWEGO W KOZIENICACH")]
        Item1408NACZELNIKURZĘDUSKARBOWEGOWKOZIENICACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1409 - NACZELNIK URZĘDU SKARBOWEGO W LEGIONOWIE")]
        Item1409NACZELNIKURZĘDUSKARBOWEGOWLEGIONOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1410 - NACZELNIK URZĘDU SKARBOWEGO W ŁOSICACH")]
        Item1410NACZELNIKURZĘDUSKARBOWEGOWŁOSICACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1411 - NACZELNIK URZĘDU SKARBOWEGO W MAKOWIE MAZOWIECKIM")]
        Item1411NACZELNIKURZĘDUSKARBOWEGOWMAKOWIEMAZOWIECKIM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1412 - NACZELNIK URZĘDU SKARBOWEGO W MIŃSKU MAZOWIECKIM")]
        Item1412NACZELNIKURZĘDUSKARBOWEGOWMIŃSKUMAZOWIECKIM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1413 - NACZELNIK URZĘDU SKARBOWEGO W MŁAWIE")]
        Item1413NACZELNIKURZĘDUSKARBOWEGOWMŁAWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1414 - NACZELNIK URZĘDU SKARBOWEGO W NOWYM DWORZE MAZOWIECKIM")]
        Item1414NACZELNIKURZĘDUSKARBOWEGOWNOWYMDWORZEMAZOWIECKIM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1415 - NACZELNIK URZĘDU SKARBOWEGO W OSTROŁĘCE")]
        Item1415NACZELNIKURZĘDUSKARBOWEGOWOSTROŁĘCE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1416 - NACZELNIK URZĘDU SKARBOWEGO W OSTROWI MAZOWIECKIEJ")]
        Item1416NACZELNIKURZĘDUSKARBOWEGOWOSTROWIMAZOWIECKIEJ,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1417 - NACZELNIK URZĘDU SKARBOWEGO W OTWOCKU")]
        Item1417NACZELNIKURZĘDUSKARBOWEGOWOTWOCKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1418 - NACZELNIK URZĘDU SKARBOWEGO W PIASECZNIE")]
        Item1418NACZELNIKURZĘDUSKARBOWEGOWPIASECZNIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1419 - NACZELNIK URZĘDU SKARBOWEGO W PŁOCKU")]
        Item1419NACZELNIKURZĘDUSKARBOWEGOWPŁOCKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1420 - NACZELNIK URZĘDU SKARBOWEGO W PŁOŃSKU")]
        Item1420NACZELNIKURZĘDUSKARBOWEGOWPŁOŃSKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1421 - NACZELNIK URZĘDU SKARBOWEGO W PRUSZKOWIE")]
        Item1421NACZELNIKURZĘDUSKARBOWEGOWPRUSZKOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1422 - NACZELNIK URZĘDU SKARBOWEGO W PRZASNYSZU")]
        Item1422NACZELNIKURZĘDUSKARBOWEGOWPRZASNYSZU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1423 - NACZELNIK URZĘDU SKARBOWEGO W PUŁTUSKU")]
        Item1423NACZELNIKURZĘDUSKARBOWEGOWPUŁTUSKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1424 - NACZELNIK PIERWSZEGO URZĘDU SKARBOWEGO W RADOMIU")]
        Item1424NACZELNIKPIERWSZEGOURZĘDUSKARBOWEGOWRADOMIU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1425 - NACZELNIK DRUGIEGO URZĘDU SKARBOWEGO W RADOMIU")]
        Item1425NACZELNIKDRUGIEGOURZĘDUSKARBOWEGOWRADOMIU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1426 - NACZELNIK URZĘDU SKARBOWEGO W SIEDLCACH")]
        Item1426NACZELNIKURZĘDUSKARBOWEGOWSIEDLCACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1427 - NACZELNIK URZĘDU SKARBOWEGO W SIERPCU")]
        Item1427NACZELNIKURZĘDUSKARBOWEGOWSIERPCU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1428 - NACZELNIK URZĘDU SKARBOWEGO W SOCHACZEWIE")]
        Item1428NACZELNIKURZĘDUSKARBOWEGOWSOCHACZEWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1429 - NACZELNIK URZĘDU SKARBOWEGO W SOKOŁOWIE PODLASKIM")]
        Item1429NACZELNIKURZĘDUSKARBOWEGOWSOKOŁOWIEPODLASKIM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1430 - NACZELNIK URZĘDU SKARBOWEGO W SZYDŁOWCU")]
        Item1430NACZELNIKURZĘDUSKARBOWEGOWSZYDŁOWCU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1431 - NACZELNIK URZĘDU SKARBOWEGO WARSZAWA-BEMOWO")]
        Item1431NACZELNIKURZĘDUSKARBOWEGOWARSZAWABEMOWO,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1432 - NACZELNIK URZĘDU SKARBOWEGO WARSZAWA-BIELANY")]
        Item1432NACZELNIKURZĘDUSKARBOWEGOWARSZAWABIELANY,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1433 - NACZELNIK URZĘDU SKARBOWEGO WARSZAWA-MOKOTÓW")]
        Item1433NACZELNIKURZĘDUSKARBOWEGOWARSZAWAMOKOTÓW,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1434 - NACZELNIK URZĘDU SKARBOWEGO WARSZAWA-PRAGA")]
        Item1434NACZELNIKURZĘDUSKARBOWEGOWARSZAWAPRAGA,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1435 - NACZELNIK PIERWSZEGO URZĘDU SKARBOWEGO WARSZAWA-ŚRÓDMIEŚCIE")]
        Item1435NACZELNIKPIERWSZEGOURZĘDUSKARBOWEGOWARSZAWAŚRÓDMIEŚCIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1436 - NACZELNIK DRUGIEGO URZĘDU SKARBOWEGO WARSZAWA-ŚRÓDMIEŚCIE")]
        Item1436NACZELNIKDRUGIEGOURZĘDUSKARBOWEGOWARSZAWAŚRÓDMIEŚCIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1437 - NACZELNIK URZĘDU SKARBOWEGO WARSZAWA-TARGÓWEK")]
        Item1437NACZELNIKURZĘDUSKARBOWEGOWARSZAWATARGÓWEK,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1438 - NACZELNIK URZĘDU SKARBOWEGO WARSZAWA-URSYNÓW")]
        Item1438NACZELNIKURZĘDUSKARBOWEGOWARSZAWAURSYNÓW,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1439 - NACZELNIK URZĘDU SKARBOWEGO WARSZAWA-WAWER")]
        Item1439NACZELNIKURZĘDUSKARBOWEGOWARSZAWAWAWER,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1440 - NACZELNIK URZĘDU SKARBOWEGO WARSZAWA-WOLA")]
        Item1440NACZELNIKURZĘDUSKARBOWEGOWARSZAWAWOLA,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1441 - NACZELNIK URZĘDU SKARBOWEGO W WĘGROWIE")]
        Item1441NACZELNIKURZĘDUSKARBOWEGOWWĘGROWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1442 - NACZELNIK URZĘDU SKARBOWEGO W WOŁOMINIE")]
        Item1442NACZELNIKURZĘDUSKARBOWEGOWWOŁOMINIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1443 - NACZELNIK URZĘDU SKARBOWEGO W WYSZKOWIE")]
        Item1443NACZELNIKURZĘDUSKARBOWEGOWWYSZKOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1444 - NACZELNIK URZĘDU SKARBOWEGO W ZWOLENIU")]
        Item1444NACZELNIKURZĘDUSKARBOWEGOWZWOLENIU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1445 - NACZELNIK URZĘDU SKARBOWEGO W ŻUROMINIE")]
        Item1445NACZELNIKURZĘDUSKARBOWEGOWŻUROMINIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1446 - NACZELNIK URZĘDU SKARBOWEGO W ŻYRARDOWIE")]
        Item1446NACZELNIKURZĘDUSKARBOWEGOWŻYRARDOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1447 - NACZELNIK URZĘDU SKARBOWEGO W LIPSKU")]
        Item1447NACZELNIKURZĘDUSKARBOWEGOWLIPSKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1448 - NACZELNIK URZĘDU SKARBOWEGO W PRZYSUSZE")]
        Item1448NACZELNIKURZĘDUSKARBOWEGOWPRZYSUSZE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1449 - NACZELNIK TRZECIEGO URZĘDU SKARBOWEGO WARSZAWA-ŚRÓDMIEŚCIE")]
        Item1449NACZELNIKTRZECIEGOURZĘDUSKARBOWEGOWARSZAWAŚRÓDMIEŚCIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1471 - NACZELNIK PIERWSZEGO MAZOWIECKIEGO URZĘDU SKARBOWEGO W WARSZAWIE")]
        Item1471NACZELNIKPIERWSZEGOMAZOWIECKIEGOURZĘDUSKARBOWEGOWWARSZAWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1472 - NACZELNIK DRUGIEGO MAZOWIECKIEGO URZĘDU SKARBOWEGO W WARSZAWIE")]
        Item1472NACZELNIKDRUGIEGOMAZOWIECKIEGOURZĘDUSKARBOWEGOWWARSZAWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1473 - NACZELNIK TRZECIEGO MAZOWIECKIEGO URZĘDU SKARBOWEGO W RADOMIU")]
        Item1473NACZELNIKTRZECIEGOMAZOWIECKIEGOURZĘDUSKARBOWEGOWRADOMIU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1602 - NACZELNIK URZĘDU SKARBOWEGO W BRZEGU")]
        Item1602NACZELNIKURZĘDUSKARBOWEGOWBRZEGU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1603 - NACZELNIK URZĘDU SKARBOWEGO W GŁUBCZYCACH")]
        Item1603NACZELNIKURZĘDUSKARBOWEGOWGŁUBCZYCACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1604 - NACZELNIK URZĘDU SKARBOWEGO W KĘDZIERZYNIE-KOŹLU")]
        Item1604NACZELNIKURZĘDUSKARBOWEGOWKĘDZIERZYNIEKOŹLU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1605 - NACZELNIK URZĘDU SKARBOWEGO W KLUCZBORKU")]
        Item1605NACZELNIKURZĘDUSKARBOWEGOWKLUCZBORKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1606 - NACZELNIK URZĘDU SKARBOWEGO W NAMYSŁOWIE")]
        Item1606NACZELNIKURZĘDUSKARBOWEGOWNAMYSŁOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1607 - NACZELNIK URZĘDU SKARBOWEGO W NYSIE")]
        Item1607NACZELNIKURZĘDUSKARBOWEGOWNYSIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1608 - NACZELNIK URZĘDU SKARBOWEGO W OLEŚNIE")]
        Item1608NACZELNIKURZĘDUSKARBOWEGOWOLEŚNIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1609 - NACZELNIK PIERWSZEGO URZĘDU SKARBOWEGO W OPOLU")]
        Item1609NACZELNIKPIERWSZEGOURZĘDUSKARBOWEGOWOPOLU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1610 - NACZELNIK DRUGIEGO URZĘDU SKARBOWEGO W OPOLU")]
        Item1610NACZELNIKDRUGIEGOURZĘDUSKARBOWEGOWOPOLU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1611 - NACZELNIK URZĘDU SKARBOWEGO W PRUDNIKU")]
        Item1611NACZELNIKURZĘDUSKARBOWEGOWPRUDNIKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1612 - NACZELNIK URZĘDU SKARBOWEGO W STRZELCACH OPOLSKICH")]
        Item1612NACZELNIKURZĘDUSKARBOWEGOWSTRZELCACHOPOLSKICH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1613 - NACZELNIK URZĘDU SKARBOWEGO W KRAPKOWICACH")]
        Item1613NACZELNIKURZĘDUSKARBOWEGOWKRAPKOWICACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1671 - NACZELNIK OPOLSKIEGO URZĘDU SKARBOWEGO W OPOLU")]
        Item1671NACZELNIKOPOLSKIEGOURZĘDUSKARBOWEGOWOPOLU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1802 - NACZELNIK URZĘDU SKARBOWEGO W BRZOZOWIE")]
        Item1802NACZELNIKURZĘDUSKARBOWEGOWBRZOZOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1803 - NACZELNIK URZĘDU SKARBOWEGO W DĘBICY")]
        Item1803NACZELNIKURZĘDUSKARBOWEGOWDĘBICY,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1804 - NACZELNIK URZĘDU SKARBOWEGO W JAROSŁAWIU")]
        Item1804NACZELNIKURZĘDUSKARBOWEGOWJAROSŁAWIU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1805 - NACZELNIK URZĘDU SKARBOWEGO W JAŚLE")]
        Item1805NACZELNIKURZĘDUSKARBOWEGOWJAŚLE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1806 - NACZELNIK URZĘDU SKARBOWEGO W KOLBUSZOWEJ")]
        Item1806NACZELNIKURZĘDUSKARBOWEGOWKOLBUSZOWEJ,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1807 - NACZELNIK URZĘDU SKARBOWEGO W KROŚNIE")]
        Item1807NACZELNIKURZĘDUSKARBOWEGOWKROŚNIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1808 - NACZELNIK URZĘDU SKARBOWEGO W LESKU")]
        Item1808NACZELNIKURZĘDUSKARBOWEGOWLESKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1809 - NACZELNIK URZĘDU SKARBOWEGO W LEŻAJSKU")]
        Item1809NACZELNIKURZĘDUSKARBOWEGOWLEŻAJSKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1810 - NACZELNIK URZĘDU SKARBOWEGO W LUBACZOWIE")]
        Item1810NACZELNIKURZĘDUSKARBOWEGOWLUBACZOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1811 - NACZELNIK URZĘDU SKARBOWEGO W ŁAŃCUCIE")]
        Item1811NACZELNIKURZĘDUSKARBOWEGOWŁAŃCUCIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1812 - NACZELNIK URZĘDU SKARBOWEGO W MIELCU")]
        Item1812NACZELNIKURZĘDUSKARBOWEGOWMIELCU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1813 - NACZELNIK URZĘDU SKARBOWEGO W PRZEMYŚLU")]
        Item1813NACZELNIKURZĘDUSKARBOWEGOWPRZEMYŚLU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1814 - NACZELNIK URZĘDU SKARBOWEGO W PRZEWORSKU")]
        Item1814NACZELNIKURZĘDUSKARBOWEGOWPRZEWORSKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1815 - NACZELNIK URZĘDU SKARBOWEGO W ROPCZYCACH")]
        Item1815NACZELNIKURZĘDUSKARBOWEGOWROPCZYCACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1816 - NACZELNIK PIERWSZEGO URZĘDU SKARBOWEGO W RZESZOWIE")]
        Item1816NACZELNIKPIERWSZEGOURZĘDUSKARBOWEGOWRZESZOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1817 - NACZELNIK URZĘDU SKARBOWEGO W SANOKU")]
        Item1817NACZELNIKURZĘDUSKARBOWEGOWSANOKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1818 - NACZELNIK URZĘDU SKARBOWEGO W STALOWEJ WOLI")]
        Item1818NACZELNIKURZĘDUSKARBOWEGOWSTALOWEJWOLI,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1819 - NACZELNIK URZĘDU SKARBOWEGO W STRZYŻOWIE")]
        Item1819NACZELNIKURZĘDUSKARBOWEGOWSTRZYŻOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1820 - NACZELNIK URZĘDU SKARBOWEGO W TARNOBRZEGU")]
        Item1820NACZELNIKURZĘDUSKARBOWEGOWTARNOBRZEGU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1821 - NACZELNIK URZĘDU SKARBOWEGO W USTRZYKACH DOLNYCH")]
        Item1821NACZELNIKURZĘDUSKARBOWEGOWUSTRZYKACHDOLNYCH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1822 - NACZELNIK DRUGIEGO URZĘDU SKARBOWEGO W RZESZOWIE")]
        Item1822NACZELNIKDRUGIEGOURZĘDUSKARBOWEGOWRZESZOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1823 - NACZELNIK URZĘDU SKARBOWEGO W NISKU")]
        Item1823NACZELNIKURZĘDUSKARBOWEGOWNISKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1871 - NACZELNIK PODKARPACKIEGO URZĘDU SKARBOWEGO W RZESZOWIE")]
        Item1871NACZELNIKPODKARPACKIEGOURZĘDUSKARBOWEGOWRZESZOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2002 - NACZELNIK URZĘDU SKARBOWEGO W AUGUSTOWIE")]
        Item2002NACZELNIKURZĘDUSKARBOWEGOWAUGUSTOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2003 - NACZELNIK PIERWSZEGO URZĘDU SKARBOWEGO W BIAŁYMSTOKU")]
        Item2003NACZELNIKPIERWSZEGOURZĘDUSKARBOWEGOWBIAŁYMSTOKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2004 - NACZELNIK DRUGIEGO URZĘDU SKARBOWEGO W BIAŁYMSTOKU")]
        Item2004NACZELNIKDRUGIEGOURZĘDUSKARBOWEGOWBIAŁYMSTOKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2005 - NACZELNIK URZĘDU SKARBOWEGO W BIELSKU PODLASKIM")]
        Item2005NACZELNIKURZĘDUSKARBOWEGOWBIELSKUPODLASKIM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2006 - NACZELNIK URZĘDU SKARBOWEGO W GRAJEWIE")]
        Item2006NACZELNIKURZĘDUSKARBOWEGOWGRAJEWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2007 - NACZELNIK URZĘDU SKARBOWEGO W KOLNIE")]
        Item2007NACZELNIKURZĘDUSKARBOWEGOWKOLNIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2008 - NACZELNIK URZĘDU SKARBOWEGO W ŁOMŻY")]
        Item2008NACZELNIKURZĘDUSKARBOWEGOWŁOMŻY,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2009 - NACZELNIK URZĘDU SKARBOWEGO W MOŃKACH")]
        Item2009NACZELNIKURZĘDUSKARBOWEGOWMOŃKACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2010 - NACZELNIK URZĘDU SKARBOWEGO W SIEMIATYCZACH")]
        Item2010NACZELNIKURZĘDUSKARBOWEGOWSIEMIATYCZACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2011 - NACZELNIK URZĘDU SKARBOWEGO W SOKÓŁCE")]
        Item2011NACZELNIKURZĘDUSKARBOWEGOWSOKÓŁCE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2012 - NACZELNIK URZĘDU SKARBOWEGO W SUWAŁKACH")]
        Item2012NACZELNIKURZĘDUSKARBOWEGOWSUWAŁKACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2013 - NACZELNIK URZĘDU SKARBOWEGO W WYSOKIEM MAZOWIECKIEM")]
        Item2013NACZELNIKURZĘDUSKARBOWEGOWWYSOKIEMMAZOWIECKIEM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2014 - NACZELNIK URZĘDU SKARBOWEGO W ZAMBROWIE")]
        Item2014NACZELNIKURZĘDUSKARBOWEGOWZAMBROWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2015 - NACZELNIK URZĘDU SKARBOWEGO W HAJNÓWCE")]
        Item2015NACZELNIKURZĘDUSKARBOWEGOWHAJNÓWCE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2071 - NACZELNIK PODLASKIEGO URZĘDU SKARBOWEGO W BIAŁYMSTOKU")]
        Item2071NACZELNIKPODLASKIEGOURZĘDUSKARBOWEGOWBIAŁYMSTOKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2202 - NACZELNIK URZĘDU SKARBOWEGO W BYTOWIE")]
        Item2202NACZELNIKURZĘDUSKARBOWEGOWBYTOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2203 - NACZELNIK URZĘDU SKARBOWEGO W CHOJNICACH")]
        Item2203NACZELNIKURZĘDUSKARBOWEGOWCHOJNICACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2204 - NACZELNIK URZĘDU SKARBOWEGO W CZŁUCHOWIE")]
        Item2204NACZELNIKURZĘDUSKARBOWEGOWCZŁUCHOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2205 - NACZELNIK PIERWSZEGO URZĘDU SKARBOWEGO W GDAŃSKU")]
        Item2205NACZELNIKPIERWSZEGOURZĘDUSKARBOWEGOWGDAŃSKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2206 - NACZELNIK DRUGIEGO URZĘDU SKARBOWEGO W GDAŃSKU")]
        Item2206NACZELNIKDRUGIEGOURZĘDUSKARBOWEGOWGDAŃSKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2207 - NACZELNIK TRZECIEGO URZĘDU SKARBOWEGO W GDAŃSKU")]
        Item2207NACZELNIKTRZECIEGOURZĘDUSKARBOWEGOWGDAŃSKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2208 - NACZELNIK PIERWSZEGO URZĘDU SKARBOWEGO W GDYNI")]
        Item2208NACZELNIKPIERWSZEGOURZĘDUSKARBOWEGOWGDYNI,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2209 - NACZELNIK DRUGIEGO URZĘDU SKARBOWEGO W GDYNI")]
        Item2209NACZELNIKDRUGIEGOURZĘDUSKARBOWEGOWGDYNI,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2210 - NACZELNIK URZĘDU SKARBOWEGO W KARTUZACH")]
        Item2210NACZELNIKURZĘDUSKARBOWEGOWKARTUZACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2211 - NACZELNIK URZĘDU SKARBOWEGO W KOŚCIERZYNIE")]
        Item2211NACZELNIKURZĘDUSKARBOWEGOWKOŚCIERZYNIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2212 - NACZELNIK URZĘDU SKARBOWEGO W KWIDZYNIE")]
        Item2212NACZELNIKURZĘDUSKARBOWEGOWKWIDZYNIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2213 - NACZELNIK URZĘDU SKARBOWEGO W LĘBORKU")]
        Item2213NACZELNIKURZĘDUSKARBOWEGOWLĘBORKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2214 - NACZELNIK URZĘDU SKARBOWEGO W MALBORKU")]
        Item2214NACZELNIKURZĘDUSKARBOWEGOWMALBORKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2215 - NACZELNIK URZĘDU SKARBOWEGO W PUCKU")]
        Item2215NACZELNIKURZĘDUSKARBOWEGOWPUCKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2216 - NACZELNIK URZĘDU SKARBOWEGO W SŁUPSKU")]
        Item2216NACZELNIKURZĘDUSKARBOWEGOWSŁUPSKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2217 - NACZELNIK URZĘDU SKARBOWEGO W SOPOCIE")]
        Item2217NACZELNIKURZĘDUSKARBOWEGOWSOPOCIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2218 - NACZELNIK URZĘDU SKARBOWEGO W STAROGARDZIE GDAŃSKIM")]
        Item2218NACZELNIKURZĘDUSKARBOWEGOWSTAROGARDZIEGDAŃSKIM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2219 - NACZELNIK URZĘDU SKARBOWEGO W TCZEWIE")]
        Item2219NACZELNIKURZĘDUSKARBOWEGOWTCZEWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2220 - NACZELNIK URZĘDU SKARBOWEGO W WEJHEROWIE")]
        Item2220NACZELNIKURZĘDUSKARBOWEGOWWEJHEROWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2221 - NACZELNIK URZĘDU SKARBOWEGO W PRUSZCZU GDAŃSKIM")]
        Item2221NACZELNIKURZĘDUSKARBOWEGOWPRUSZCZUGDAŃSKIM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2271 - NACZELNIK POMORSKIEGO URZĘDU SKARBOWEGO W GDAŃSKU")]
        Item2271NACZELNIKPOMORSKIEGOURZĘDUSKARBOWEGOWGDAŃSKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2402 - NACZELNIK URZĘDU SKARBOWEGO W BĘDZINIE")]
        Item2402NACZELNIKURZĘDUSKARBOWEGOWBĘDZINIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2403 - NACZELNIK PIERWSZEGO URZĘDU SKARBOWEGO W BIELSKU-BIAŁEJ")]
        Item2403NACZELNIKPIERWSZEGOURZĘDUSKARBOWEGOWBIELSKUBIAŁEJ,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2404 - NACZELNIK DRUGIEGO URZĘDU SKARBOWEGO W BIELSKU-BIAŁEJ")]
        Item2404NACZELNIKDRUGIEGOURZĘDUSKARBOWEGOWBIELSKUBIAŁEJ,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2405 - NACZELNIK URZĘDU SKARBOWEGO W BYTOMIU")]
        Item2405NACZELNIKURZĘDUSKARBOWEGOWBYTOMIU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2406 - NACZELNIK URZĘDU SKARBOWEGO W CHORZOWIE")]
        Item2406NACZELNIKURZĘDUSKARBOWEGOWCHORZOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2407 - NACZELNIK URZĘDU SKARBOWEGO W CIESZYNIE")]
        Item2407NACZELNIKURZĘDUSKARBOWEGOWCIESZYNIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2408 - NACZELNIK URZĘDU SKARBOWEGO W CZECHOWICACH-DZIEDZICACH")]
        Item2408NACZELNIKURZĘDUSKARBOWEGOWCZECHOWICACHDZIEDZICACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2409 - NACZELNIK PIERWSZEGO URZĘDU SKARBOWEGO W CZĘSTOCHOWIE")]
        Item2409NACZELNIKPIERWSZEGOURZĘDUSKARBOWEGOWCZĘSTOCHOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2410 - NACZELNIK DRUGIEGO URZĘDU SKARBOWEGO W CZĘSTOCHOWIE")]
        Item2410NACZELNIKDRUGIEGOURZĘDUSKARBOWEGOWCZĘSTOCHOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2411 - NACZELNIK URZĘDU SKARBOWEGO W DĄBROWIE GÓRNICZEJ")]
        Item2411NACZELNIKURZĘDUSKARBOWEGOWDĄBROWIEGÓRNICZEJ,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2412 - NACZELNIK PIERWSZEGO URZĘDU SKARBOWEGO W GLIWICACH")]
        Item2412NACZELNIKPIERWSZEGOURZĘDUSKARBOWEGOWGLIWICACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2413 - NACZELNIK DRUGIEGO URZĘDU SKARBOWEGO W GLIWICACH")]
        Item2413NACZELNIKDRUGIEGOURZĘDUSKARBOWEGOWGLIWICACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2414 - NACZELNIK URZĘDU SKARBOWEGO W JASTRZĘBIU-ZDROJU")]
        Item2414NACZELNIKURZĘDUSKARBOWEGOWJASTRZĘBIUZDROJU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2415 - NACZELNIK URZĘDU SKARBOWEGO W JAWORZNIE")]
        Item2415NACZELNIKURZĘDUSKARBOWEGOWJAWORZNIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2416 - NACZELNIK PIERWSZEGO URZĘDU SKARBOWEGO W KATOWICACH")]
        Item2416NACZELNIKPIERWSZEGOURZĘDUSKARBOWEGOWKATOWICACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2417 - NACZELNIK DRUGIEGO URZĘDU SKARBOWEGO W KATOWICACH")]
        Item2417NACZELNIKDRUGIEGOURZĘDUSKARBOWEGOWKATOWICACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2418 - NACZELNIK URZĘDU SKARBOWEGO W KŁOBUCKU")]
        Item2418NACZELNIKURZĘDUSKARBOWEGOWKŁOBUCKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2419 - NACZELNIK URZĘDU SKARBOWEGO W LUBLIŃCU")]
        Item2419NACZELNIKURZĘDUSKARBOWEGOWLUBLIŃCU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2420 - NACZELNIK URZĘDU SKARBOWEGO W MIKOŁOWIE")]
        Item2420NACZELNIKURZĘDUSKARBOWEGOWMIKOŁOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2421 - NACZELNIK URZĘDU SKARBOWEGO W MYSŁOWICACH")]
        Item2421NACZELNIKURZĘDUSKARBOWEGOWMYSŁOWICACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2422 - NACZELNIK URZĘDU SKARBOWEGO W MYSZKOWIE")]
        Item2422NACZELNIKURZĘDUSKARBOWEGOWMYSZKOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2423 - NACZELNIK URZĘDU SKARBOWEGO W PIEKARACH ŚLĄSKICH")]
        Item2423NACZELNIKURZĘDUSKARBOWEGOWPIEKARACHŚLĄSKICH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2424 - NACZELNIK URZĘDU SKARBOWEGO W PSZCZYNIE")]
        Item2424NACZELNIKURZĘDUSKARBOWEGOWPSZCZYNIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2425 - NACZELNIK URZĘDU SKARBOWEGO W RACIBORZU")]
        Item2425NACZELNIKURZĘDUSKARBOWEGOWRACIBORZU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2426 - NACZELNIK URZĘDU SKARBOWEGO W RUDZIE ŚLĄSKIEJ")]
        Item2426NACZELNIKURZĘDUSKARBOWEGOWRUDZIEŚLĄSKIEJ,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2427 - NACZELNIK URZĘDU SKARBOWEGO W RYBNIKU")]
        Item2427NACZELNIKURZĘDUSKARBOWEGOWRYBNIKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2428 - NACZELNIK URZĘDU SKARBOWEGO W SIEMIANOWICACH ŚLĄSKICH")]
        Item2428NACZELNIKURZĘDUSKARBOWEGOWSIEMIANOWICACHŚLĄSKICH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2429 - NACZELNIK URZĘDU SKARBOWEGO W SOSNOWCU")]
        Item2429NACZELNIKURZĘDUSKARBOWEGOWSOSNOWCU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2430 - NACZELNIK URZĘDU SKARBOWEGO W TARNOWSKICH GÓRACH")]
        Item2430NACZELNIKURZĘDUSKARBOWEGOWTARNOWSKICHGÓRACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2431 - NACZELNIK URZĘDU SKARBOWEGO W TYCHACH")]
        Item2431NACZELNIKURZĘDUSKARBOWEGOWTYCHACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2432 - NACZELNIK URZĘDU SKARBOWEGO W WODZISŁAWIU ŚLĄSKIM")]
        Item2432NACZELNIKURZĘDUSKARBOWEGOWWODZISŁAWIUŚLĄSKIM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2433 - NACZELNIK URZĘDU SKARBOWEGO W ZABRZU")]
        Item2433NACZELNIKURZĘDUSKARBOWEGOWZABRZU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2434 - NACZELNIK URZĘDU SKARBOWEGO W ZAWIERCIU")]
        Item2434NACZELNIKURZĘDUSKARBOWEGOWZAWIERCIU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2435 - NACZELNIK URZĘDU SKARBOWEGO W ŻORACH")]
        Item2435NACZELNIKURZĘDUSKARBOWEGOWŻORACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2436 - NACZELNIK URZĘDU SKARBOWEGO W ŻYWCU")]
        Item2436NACZELNIKURZĘDUSKARBOWEGOWŻYWCU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2471 - NACZELNIK PIERWSZEGO ŚLĄSKIEGO URZĘDU SKARBOWEGO W SOSNOWCU")]
        Item2471NACZELNIKPIERWSZEGOŚLĄSKIEGOURZĘDUSKARBOWEGOWSOSNOWCU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2472 - NACZELNIK DRUGIEGO ŚLĄSKIEGO URZĘDU SKARBOWEGO W BIELSKU-BIAŁEJ")]
        Item2472NACZELNIKDRUGIEGOŚLĄSKIEGOURZĘDUSKARBOWEGOWBIELSKUBIAŁEJ,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2602 - NACZELNIK URZĘDU SKARBOWEGO W BUSKU-ZDROJU")]
        Item2602NACZELNIKURZĘDUSKARBOWEGOWBUSKUZDROJU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2603 - NACZELNIK URZĘDU SKARBOWEGO W JĘDRZEJOWIE")]
        Item2603NACZELNIKURZĘDUSKARBOWEGOWJĘDRZEJOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2604 - NACZELNIK PIERWSZEGO URZĘDU SKARBOWEGO W KIELCACH")]
        Item2604NACZELNIKPIERWSZEGOURZĘDUSKARBOWEGOWKIELCACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2605 - NACZELNIK DRUGIEGO URZĘDU SKARBOWEGO W KIELCACH")]
        Item2605NACZELNIKDRUGIEGOURZĘDUSKARBOWEGOWKIELCACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2606 - NACZELNIK URZĘDU SKARBOWEGO W KOŃSKICH")]
        Item2606NACZELNIKURZĘDUSKARBOWEGOWKOŃSKICH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2607 - NACZELNIK URZĘDU SKARBOWEGO W OPATOWIE")]
        Item2607NACZELNIKURZĘDUSKARBOWEGOWOPATOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2608 - NACZELNIK URZĘDU SKARBOWEGO W OSTROWCU ŚWIĘTOKRZYSKIM")]
        Item2608NACZELNIKURZĘDUSKARBOWEGOWOSTROWCUŚWIĘTOKRZYSKIM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2609 - NACZELNIK URZĘDU SKARBOWEGO W PIŃCZOWIE")]
        Item2609NACZELNIKURZĘDUSKARBOWEGOWPIŃCZOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2610 - NACZELNIK URZĘDU SKARBOWEGO W SANDOMIERZU")]
        Item2610NACZELNIKURZĘDUSKARBOWEGOWSANDOMIERZU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2611 - NACZELNIK URZĘDU SKARBOWEGO W SKARŻYSKU-KAMIENNEJ")]
        Item2611NACZELNIKURZĘDUSKARBOWEGOWSKARŻYSKUKAMIENNEJ,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2612 - NACZELNIK URZĘDU SKARBOWEGO W STARACHOWICACH")]
        Item2612NACZELNIKURZĘDUSKARBOWEGOWSTARACHOWICACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2613 - NACZELNIK URZĘDU SKARBOWEGO W STASZOWIE")]
        Item2613NACZELNIKURZĘDUSKARBOWEGOWSTASZOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2614 - NACZELNIK URZĘDU SKARBOWEGO W KAZIMIERZY WIELKIEJ")]
        Item2614NACZELNIKURZĘDUSKARBOWEGOWKAZIMIERZYWIELKIEJ,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2615 - NACZELNIK URZĘDU SKARBOWEGO WE WŁOSZCZOWIE")]
        Item2615NACZELNIKURZĘDUSKARBOWEGOWEWŁOSZCZOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2671 - NACZELNIK ŚWIĘTOKRZYSKIEGO URZĘDU SKARBOWEGO W KIELCACH")]
        Item2671NACZELNIKŚWIĘTOKRZYSKIEGOURZĘDUSKARBOWEGOWKIELCACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2802 - NACZELNIK URZĘDU SKARBOWEGO W BARTOSZYCACH")]
        Item2802NACZELNIKURZĘDUSKARBOWEGOWBARTOSZYCACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2803 - NACZELNIK URZĘDU SKARBOWEGO W BRANIEWIE")]
        Item2803NACZELNIKURZĘDUSKARBOWEGOWBRANIEWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2804 - NACZELNIK URZĘDU SKARBOWEGO W DZIAŁDOWIE")]
        Item2804NACZELNIKURZĘDUSKARBOWEGOWDZIAŁDOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2805 - NACZELNIK URZĘDU SKARBOWEGO W ELBLĄGU")]
        Item2805NACZELNIKURZĘDUSKARBOWEGOWELBLĄGU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2806 - NACZELNIK URZĘDU SKARBOWEGO W EŁKU")]
        Item2806NACZELNIKURZĘDUSKARBOWEGOWEŁKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2807 - NACZELNIK URZĘDU SKARBOWEGO W GIŻYCKU")]
        Item2807NACZELNIKURZĘDUSKARBOWEGOWGIŻYCKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2808 - NACZELNIK URZĘDU SKARBOWEGO W IŁAWIE")]
        Item2808NACZELNIKURZĘDUSKARBOWEGOWIŁAWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2809 - NACZELNIK URZĘDU SKARBOWEGO W KĘTRZYNIE")]
        Item2809NACZELNIKURZĘDUSKARBOWEGOWKĘTRZYNIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2810 - NACZELNIK URZĘDU SKARBOWEGO W NIDZICY")]
        Item2810NACZELNIKURZĘDUSKARBOWEGOWNIDZICY,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2811 - NACZELNIK URZĘDU SKARBOWEGO W NOWYM MIEŚCIE LUBAWSKIM")]
        Item2811NACZELNIKURZĘDUSKARBOWEGOWNOWYMMIEŚCIELUBAWSKIM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2812 - NACZELNIK URZĘDU SKARBOWEGO W OLECKU")]
        Item2812NACZELNIKURZĘDUSKARBOWEGOWOLECKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2813 - NACZELNIK URZĘDU SKARBOWEGO W OLSZTYNIE")]
        Item2813NACZELNIKURZĘDUSKARBOWEGOWOLSZTYNIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2814 - NACZELNIK URZĘDU SKARBOWEGO W OSTRÓDZIE")]
        Item2814NACZELNIKURZĘDUSKARBOWEGOWOSTRÓDZIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2815 - NACZELNIK URZĘDU SKARBOWEGO W PISZU")]
        Item2815NACZELNIKURZĘDUSKARBOWEGOWPISZU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2816 - NACZELNIK URZĘDU SKARBOWEGO W SZCZYTNIE")]
        Item2816NACZELNIKURZĘDUSKARBOWEGOWSZCZYTNIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2871 - NACZELNIK WARMIŃSKO-MAZURSKIEGO URZĘDU SKARBOWEGO W OLSZTYNIE")]
        Item2871NACZELNIKWARMIŃSKOMAZURSKIEGOURZĘDUSKARBOWEGOWOLSZTYNIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3002 - NACZELNIK URZĘDU SKARBOWEGO W CZARNKOWIE")]
        Item3002NACZELNIKURZĘDUSKARBOWEGOWCZARNKOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3003 - NACZELNIK URZĘDU SKARBOWEGO W GNIEŹNIE")]
        Item3003NACZELNIKURZĘDUSKARBOWEGOWGNIEŹNIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3004 - NACZELNIK URZĘDU SKARBOWEGO W GOSTYNIU")]
        Item3004NACZELNIKURZĘDUSKARBOWEGOWGOSTYNIU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3005 - NACZELNIK URZĘDU SKARBOWEGO W GRODZISKU WIELKOPOLSKIM")]
        Item3005NACZELNIKURZĘDUSKARBOWEGOWGRODZISKUWIELKOPOLSKIM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3006 - NACZELNIK URZĘDU SKARBOWEGO W JAROCINIE")]
        Item3006NACZELNIKURZĘDUSKARBOWEGOWJAROCINIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3007 - NACZELNIK PIERWSZEGO URZĘDU SKARBOWEGO W KALISZU")]
        Item3007NACZELNIKPIERWSZEGOURZĘDUSKARBOWEGOWKALISZU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3008 - NACZELNIK DRUGIEGO URZĘDU SKARBOWEGO W KALISZU")]
        Item3008NACZELNIKDRUGIEGOURZĘDUSKARBOWEGOWKALISZU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3009 - NACZELNIK URZĘDU SKARBOWEGO W KĘPNIE")]
        Item3009NACZELNIKURZĘDUSKARBOWEGOWKĘPNIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3010 - NACZELNIK URZĘDU SKARBOWEGO W KOLE")]
        Item3010NACZELNIKURZĘDUSKARBOWEGOWKOLE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3011 - NACZELNIK URZĘDU SKARBOWEGO W KONINIE")]
        Item3011NACZELNIKURZĘDUSKARBOWEGOWKONINIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3012 - NACZELNIK URZĘDU SKARBOWEGO W KOŚCIANIE")]
        Item3012NACZELNIKURZĘDUSKARBOWEGOWKOŚCIANIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3013 - NACZELNIK URZĘDU SKARBOWEGO W KROTOSZYNIE")]
        Item3013NACZELNIKURZĘDUSKARBOWEGOWKROTOSZYNIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3014 - NACZELNIK URZĘDU SKARBOWEGO W LESZNIE")]
        Item3014NACZELNIKURZĘDUSKARBOWEGOWLESZNIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3015 - NACZELNIK URZĘDU SKARBOWEGO W MIĘDZYCHODZIE")]
        Item3015NACZELNIKURZĘDUSKARBOWEGOWMIĘDZYCHODZIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3016 - NACZELNIK URZĘDU SKARBOWEGO W NOWYM TOMYŚLU")]
        Item3016NACZELNIKURZĘDUSKARBOWEGOWNOWYMTOMYŚLU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3017 - NACZELNIK URZĘDU SKARBOWEGO W OSTROWIE WIELKOPOLSKIM")]
        Item3017NACZELNIKURZĘDUSKARBOWEGOWOSTROWIEWIELKOPOLSKIM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3018 - NACZELNIK URZĘDU SKARBOWEGO W OSTRZESZOWIE")]
        Item3018NACZELNIKURZĘDUSKARBOWEGOWOSTRZESZOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3019 - NACZELNIK URZĘDU SKARBOWEGO W PILE")]
        Item3019NACZELNIKURZĘDUSKARBOWEGOWPILE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3020 - NACZELNIK URZĘDU SKARBOWEGO POZNAŃ-GRUNWALD")]
        Item3020NACZELNIKURZĘDUSKARBOWEGOPOZNAŃGRUNWALD,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3021 - NACZELNIK URZĘDU SKARBOWEGO POZNAŃ-JEŻYCE")]
        Item3021NACZELNIKURZĘDUSKARBOWEGOPOZNAŃJEŻYCE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3022 - NACZELNIK URZĘDU SKARBOWEGO POZNAŃ-NOWE MIASTO")]
        Item3022NACZELNIKURZĘDUSKARBOWEGOPOZNAŃNOWEMIASTO,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3023 - NACZELNIK PIERWSZEGO URZĘDU SKARBOWEGO W POZNANIU")]
        Item3023NACZELNIKPIERWSZEGOURZĘDUSKARBOWEGOWPOZNANIU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3025 - NACZELNIK URZĘDU SKARBOWEGO POZNAŃ-WINOGRADY")]
        Item3025NACZELNIKURZĘDUSKARBOWEGOPOZNAŃWINOGRADY,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3026 - NACZELNIK URZĘDU SKARBOWEGO POZNAŃ-WILDA")]
        Item3026NACZELNIKURZĘDUSKARBOWEGOPOZNAŃWILDA,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3027 - NACZELNIK URZĘDU SKARBOWEGO W RAWICZU")]
        Item3027NACZELNIKURZĘDUSKARBOWEGOWRAWICZU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3028 - NACZELNIK URZĘDU SKARBOWEGO W SŁUPCY")]
        Item3028NACZELNIKURZĘDUSKARBOWEGOWSŁUPCY,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3029 - NACZELNIK URZĘDU SKARBOWEGO W SZAMOTUŁACH")]
        Item3029NACZELNIKURZĘDUSKARBOWEGOWSZAMOTUŁACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3030 - NACZELNIK URZĘDU SKARBOWEGO W ŚREMIE")]
        Item3030NACZELNIKURZĘDUSKARBOWEGOWŚREMIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3031 - NACZELNIK URZĘDU SKARBOWEGO W ŚRODZIE WIELKOPOLSKIEJ")]
        Item3031NACZELNIKURZĘDUSKARBOWEGOWŚRODZIEWIELKOPOLSKIEJ,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3032 - NACZELNIK URZĘDU SKARBOWEGO W TURKU")]
        Item3032NACZELNIKURZĘDUSKARBOWEGOWTURKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3033 - NACZELNIK URZĘDU SKARBOWEGO W WĄGROWCU")]
        Item3033NACZELNIKURZĘDUSKARBOWEGOWWĄGROWCU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3034 - NACZELNIK URZĘDU SKARBOWEGO W WOLSZTYNIE")]
        Item3034NACZELNIKURZĘDUSKARBOWEGOWWOLSZTYNIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3035 - NACZELNIK URZĘDU SKARBOWEGO WE WRZEŚNI")]
        Item3035NACZELNIKURZĘDUSKARBOWEGOWEWRZEŚNI,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3036 - NACZELNIK URZĘDU SKARBOWEGO W ZŁOTOWIE")]
        Item3036NACZELNIKURZĘDUSKARBOWEGOWZŁOTOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3037 - NACZELNIK URZĘDU SKARBOWEGO W CHODZIEŻY")]
        Item3037NACZELNIKURZĘDUSKARBOWEGOWCHODZIEŻY,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3038 - NACZELNIK URZĘDU SKARBOWEGO W OBORNIKACH")]
        Item3038NACZELNIKURZĘDUSKARBOWEGOWOBORNIKACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3039 - NACZELNIK URZĘDU SKARBOWEGO W PLESZEWIE")]
        Item3039NACZELNIKURZĘDUSKARBOWEGOWPLESZEWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3071 - NACZELNIK PIERWSZEGO WIELKOPOLSKIEGO URZĘDU SKARBOWEGO W POZNANIU")]
        Item3071NACZELNIKPIERWSZEGOWIELKOPOLSKIEGOURZĘDUSKARBOWEGOWPOZNANIU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3072 - NACZELNIK DRUGIEGO WIELKOPOLSKIEGO URZĘDU SKARBOWEGO W KALISZU")]
        Item3072NACZELNIKDRUGIEGOWIELKOPOLSKIEGOURZĘDUSKARBOWEGOWKALISZU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3202 - NACZELNIK URZĘDU SKARBOWEGO W BIAŁOGARDZIE")]
        Item3202NACZELNIKURZĘDUSKARBOWEGOWBIAŁOGARDZIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3203 - NACZELNIK URZĘDU SKARBOWEGO W CHOSZCZNIE")]
        Item3203NACZELNIKURZĘDUSKARBOWEGOWCHOSZCZNIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3204 - NACZELNIK URZĘDU SKARBOWEGO W DRAWSKU POMORSKIM")]
        Item3204NACZELNIKURZĘDUSKARBOWEGOWDRAWSKUPOMORSKIM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3205 - NACZELNIK URZĘDU SKARBOWEGO W GOLENIOWIE")]
        Item3205NACZELNIKURZĘDUSKARBOWEGOWGOLENIOWIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3206 - NACZELNIK URZĘDU SKARBOWEGO W GRYFICACH")]
        Item3206NACZELNIKURZĘDUSKARBOWEGOWGRYFICACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3207 - NACZELNIK URZĘDU SKARBOWEGO W GRYFINIE")]
        Item3207NACZELNIKURZĘDUSKARBOWEGOWGRYFINIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3208 - NACZELNIK URZĘDU SKARBOWEGO W KAMIENIU POMORSKIM")]
        Item3208NACZELNIKURZĘDUSKARBOWEGOWKAMIENIUPOMORSKIM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3209 - NACZELNIK URZĘDU SKARBOWEGO W KOŁOBRZEGU")]
        Item3209NACZELNIKURZĘDUSKARBOWEGOWKOŁOBRZEGU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3210 - NACZELNIK PIERWSZEGO URZĘDU SKARBOWEGO W KOSZALINIE")]
        Item3210NACZELNIKPIERWSZEGOURZĘDUSKARBOWEGOWKOSZALINIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3211 - NACZELNIK DRUGIEGO URZĘDU SKARBOWEGO W KOSZALINIE")]
        Item3211NACZELNIKDRUGIEGOURZĘDUSKARBOWEGOWKOSZALINIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3212 - NACZELNIK URZĘDU SKARBOWEGO W MYŚLIBORZU")]
        Item3212NACZELNIKURZĘDUSKARBOWEGOWMYŚLIBORZU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3213 - NACZELNIK URZĘDU SKARBOWEGO W PYRZYCACH")]
        Item3213NACZELNIKURZĘDUSKARBOWEGOWPYRZYCACH,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3214 - NACZELNIK URZĘDU SKARBOWEGO W STARGARDZIE")]
        Item3214NACZELNIKURZĘDUSKARBOWEGOWSTARGARDZIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3215 - NACZELNIK PIERWSZEGO URZĘDU SKARBOWEGO W SZCZECINIE")]
        Item3215NACZELNIKPIERWSZEGOURZĘDUSKARBOWEGOWSZCZECINIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3216 - NACZELNIK DRUGIEGO URZĘDU SKARBOWEGO W SZCZECINIE")]
        Item3216NACZELNIKDRUGIEGOURZĘDUSKARBOWEGOWSZCZECINIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3217 - NACZELNIK TRZECIEGO URZĘDU SKARBOWEGO W SZCZECINIE")]
        Item3217NACZELNIKTRZECIEGOURZĘDUSKARBOWEGOWSZCZECINIE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3218 - NACZELNIK URZĘDU SKARBOWEGO W SZCZECINKU")]
        Item3218NACZELNIKURZĘDUSKARBOWEGOWSZCZECINKU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3219 - NACZELNIK URZĘDU SKARBOWEGO W ŚWINOUJŚCIU")]
        Item3219NACZELNIKURZĘDUSKARBOWEGOWŚWINOUJŚCIU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3220 - NACZELNIK URZĘDU SKARBOWEGO W WAŁCZU")]
        Item3220NACZELNIKURZĘDUSKARBOWEGOWWAŁCZU,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3271 - NACZELNIK ZACHODNIOPOMORSKIEGO URZĘDU SKARBOWEGO W SZCZECINIE")]
        Item3271NACZELNIKZACHODNIOPOMORSKIEGOURZĘDUSKARBOWEGOWSZCZECINIE,
    }
}
