// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.1.854 Microsoft Reciprocal License (Ms-RL) 
//    <NameSpace>JPK_generator</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace JPK_generator.XSD
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class JPK
    {

        private TNaglowek naglowekField;

        private JPKPodmiot1 podmiot1Field;

        private List<JPKSprzedazWiersz> sprzedazWierszField;

        private JPKSprzedazCtrl sprzedazCtrlField;

        private List<JPKZakupWiersz> zakupWierszField;

        private JPKZakupCtrl zakupCtrlField;

        public JPK()
        {
            this.zakupCtrlField = new JPKZakupCtrl();
            this.zakupWierszField = new List<JPKZakupWiersz>();
            this.sprzedazCtrlField = new JPKSprzedazCtrl();
            this.sprzedazWierszField = new List<JPKSprzedazWiersz>();
            this.podmiot1Field = new JPKPodmiot1();
            this.naglowekField = new TNaglowek();
        }

        public TNaglowek Naglowek
        {
            get
            {
                return this.naglowekField;
            }
            set
            {
                this.naglowekField = value;
            }
        }

        public JPKPodmiot1 Podmiot1
        {
            get
            {
                return this.podmiot1Field;
            }
            set
            {
                this.podmiot1Field = value;
            }
        }

        public List<JPKSprzedazWiersz> SprzedazWiersz
        {
            get
            {
                return this.sprzedazWierszField;
            }
            set
            {
                this.sprzedazWierszField = value;
            }
        }

        public JPKSprzedazCtrl SprzedazCtrl
        {
            get
            {
                return this.sprzedazCtrlField;
            }
            set
            {
                this.sprzedazCtrlField = value;
            }
        }

        public List<JPKZakupWiersz> ZakupWiersz
        {
            get
            {
                return this.zakupWierszField;
            }
            set
            {
                this.zakupWierszField = value;
            }
        }

        public JPKZakupCtrl ZakupCtrl
        {
            get
            {
                return this.zakupCtrlField;
            }
            set
            {
                this.zakupCtrlField = value;
            }
        }
    }

    public partial class TNaglowek
    {

        private TNaglowekKodFormularza kodFormularzaField;

        private sbyte wariantFormularzaField;

        private string celZlozeniaField;

        private System.DateTime dataWytworzeniaJPKField;

        private System.DateTime dataOdField;

        private System.DateTime dataDoField;

        private string nazwaSystemuField;

        public TNaglowek()
        {
            this.kodFormularzaField = new TNaglowekKodFormularza();
            this.celZlozeniaField = "0";
        }

        public TNaglowekKodFormularza KodFormularza
        {
            get
            {
                return this.kodFormularzaField;
            }
            set
            {
                this.kodFormularzaField = value;
            }
        }

        public sbyte WariantFormularza
        {
            get
            {
                return this.wariantFormularzaField;
            }
            set
            {
                this.wariantFormularzaField = value;
            }
        }

        public string CelZlozenia
        {
            get
            {
                return this.celZlozeniaField;
            }
            set
            {
                this.celZlozeniaField = value;
            }
        }

        public System.DateTime DataWytworzeniaJPK
        {
            get
            {
                return this.dataWytworzeniaJPKField;
            }
            set
            {
                this.dataWytworzeniaJPKField = value;
            }
        }

        public System.DateTime DataOd
        {
            get
            {
                return this.dataOdField;
            }
            set
            {
                this.dataOdField = value;
            }
        }

        public System.DateTime DataDo
        {
            get
            {
                return this.dataDoField;
            }
            set
            {
                this.dataDoField = value;
            }
        }

        public string NazwaSystemu
        {
            get
            {
                return this.nazwaSystemuField;
            }
            set
            {
                this.nazwaSystemuField = value;
            }
        }
    }

    public partial class TNaglowekKodFormularza
    {

        private string kodSystemowyField;

        private string wersjaSchemyField;

        private TKodFormularza valueField;

        public TNaglowekKodFormularza()
        {
            this.kodSystemowyField = "JPK_VAT (3)";
            this.wersjaSchemyField = "1-1";
        }

        public string kodSystemowy
        {
            get
            {
                return this.kodSystemowyField;
            }
            set
            {
                this.kodSystemowyField = value;
            }
        }

        public string wersjaSchemy
        {
            get
            {
                return this.wersjaSchemyField;
            }
            set
            {
                this.wersjaSchemyField = value;
            }
        }

        //[System.Xml.Serialization.XmlTextAttribute()]
        //public TKodFormularza Value
        //{
        //    get
        //    {
        //        return this.valueField;
        //    }
        //    set
        //    {
        //        this.valueField = value;
        //    }
        //}
    }

    public enum TKodFormularza
    {

        /// <remarks/>
        JPK_VAT,
    }

    public partial class JPKPodmiot1
    {

        private string nIPField;

        private string pelnaNazwaField;

        private string emailField;

        public string NIP
        {
            get
            {
                return this.nIPField;
            }
            set
            {
                this.nIPField = value;
            }
        }

        public string PelnaNazwa
        {
            get
            {
                return this.pelnaNazwaField;
            }
            set
            {
                this.pelnaNazwaField = value;
            }
        }

        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
    }

    public partial class JPKSprzedazWiersz
    {

        private string lpSprzedazyField;

        private string nrKontrahentaField;

        private string nazwaKontrahentaField;

        private string adresKontrahentaField;

        private string dowodSprzedazyField;

        private System.DateTime dataWystawieniaField;

        private System.DateTime dataSprzedazyField;

        private bool dataSprzedazyFieldSpecified;

        private decimal k_10Field;

        private bool k_10FieldSpecified;

        private decimal k_11Field;

        private bool k_11FieldSpecified;

        private decimal k_12Field;

        private bool k_12FieldSpecified;

        private decimal k_13Field;

        private bool k_13FieldSpecified;

        private decimal k_14Field;

        private bool k_14FieldSpecified;

        private decimal k_15Field;

        private decimal k_16Field;

        private decimal k_17Field;

        private decimal k_18Field;

        private decimal k_19Field;

        private decimal k_20Field;

        private decimal k_21Field;

        private bool k_21FieldSpecified;

        private decimal k_22Field;

        private bool k_22FieldSpecified;

        private decimal k_23Field;

        private decimal k_24Field;

        private decimal k_25Field;

        private decimal k_26Field;

        private decimal k_27Field;

        private decimal k_28Field;

        private decimal k_29Field;

        private decimal k_30Field;

        private decimal k_31Field;

        private bool k_31FieldSpecified;

        private decimal k_32Field;

        private decimal k_33Field;

        private decimal k_34Field;

        private decimal k_35Field;

        private decimal k_36Field;

        private bool k_36FieldSpecified;

        private decimal k_37Field;

        private bool k_37FieldSpecified;

        private decimal k_38Field;

        private bool k_38FieldSpecified;

        private decimal k_39Field;

        private bool k_39FieldSpecified;

        public string LpSprzedazy
        {
            get
            {
                return this.lpSprzedazyField;
            }
            set
            {
                this.lpSprzedazyField = value;
            }
        }

        public string NrKontrahenta
        {
            get
            {
                return this.nrKontrahentaField;
            }
            set
            {
                this.nrKontrahentaField = value;
            }
        }

        public string NazwaKontrahenta
        {
            get
            {
                return this.nazwaKontrahentaField;
            }
            set
            {
                this.nazwaKontrahentaField = value;
            }
        }

        public string AdresKontrahenta
        {
            get
            {
                return this.adresKontrahentaField;
            }
            set
            {
                this.adresKontrahentaField = value;
            }
        }

        public string DowodSprzedazy
        {
            get
            {
                return this.dowodSprzedazyField;
            }
            set
            {
                this.dowodSprzedazyField = value;
            }
        }

        public System.DateTime DataWystawienia
        {
            get
            {
                return this.dataWystawieniaField;
            }
            set
            {
                this.dataWystawieniaField = value;
            }
        }

        public System.DateTime DataSprzedazy
        {
            get
            {
                return this.dataSprzedazyField;
            }
            set
            {
                this.dataSprzedazyField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataSprzedazySpecified
        {
            get
            {
                return this.dataSprzedazyFieldSpecified;
            }
            set
            {
                this.dataSprzedazyFieldSpecified = value;
            }
        }

        public decimal K_10
        {
            get
            {
                return this.k_10Field;
            }
            set
            {
                this.k_10Field = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool K_10Specified
        {
            get
            {
                return this.k_10FieldSpecified;
            }
            set
            {
                this.k_10FieldSpecified = value;
            }
        }

        public decimal K_11
        {
            get
            {
                return this.k_11Field;
            }
            set
            {
                this.k_11Field = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool K_11Specified
        {
            get
            {
                return this.k_11FieldSpecified;
            }
            set
            {
                this.k_11FieldSpecified = value;
            }
        }

        public decimal K_12
        {
            get
            {
                return this.k_12Field;
            }
            set
            {
                this.k_12Field = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool K_12Specified
        {
            get
            {
                return this.k_12FieldSpecified;
            }
            set
            {
                this.k_12FieldSpecified = value;
            }
        }

        public decimal K_13
        {
            get
            {
                return this.k_13Field;
            }
            set
            {
                this.k_13Field = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool K_13Specified
        {
            get
            {
                return this.k_13FieldSpecified;
            }
            set
            {
                this.k_13FieldSpecified = value;
            }
        }

        public decimal K_14
        {
            get
            {
                return this.k_14Field;
            }
            set
            {
                this.k_14Field = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool K_14Specified
        {
            get
            {
                return this.k_14FieldSpecified;
            }
            set
            {
                this.k_14FieldSpecified = value;
            }
        }

        public decimal K_15
        {
            get
            {
                return this.k_15Field;
            }
            set
            {
                this.k_15Field = value;
            }
        }

        public decimal K_16
        {
            get
            {
                return this.k_16Field;
            }
            set
            {
                this.k_16Field = value;
            }
        }

        public decimal K_17
        {
            get
            {
                return this.k_17Field;
            }
            set
            {
                this.k_17Field = value;
            }
        }

        public decimal K_18
        {
            get
            {
                return this.k_18Field;
            }
            set
            {
                this.k_18Field = value;
            }
        }

        public decimal K_19
        {
            get
            {
                return this.k_19Field;
            }
            set
            {
                this.k_19Field = value;
            }
        }

        public decimal K_20
        {
            get
            {
                return this.k_20Field;
            }
            set
            {
                this.k_20Field = value;
            }
        }

        public decimal K_21
        {
            get
            {
                return this.k_21Field;
            }
            set
            {
                this.k_21Field = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool K_21Specified
        {
            get
            {
                return this.k_21FieldSpecified;
            }
            set
            {
                this.k_21FieldSpecified = value;
            }
        }

        public decimal K_22
        {
            get
            {
                return this.k_22Field;
            }
            set
            {
                this.k_22Field = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool K_22Specified
        {
            get
            {
                return this.k_22FieldSpecified;
            }
            set
            {
                this.k_22FieldSpecified = value;
            }
        }

        public decimal K_23
        {
            get
            {
                return this.k_23Field;
            }
            set
            {
                this.k_23Field = value;
            }
        }

        public decimal K_24
        {
            get
            {
                return this.k_24Field;
            }
            set
            {
                this.k_24Field = value;
            }
        }

        public decimal K_25
        {
            get
            {
                return this.k_25Field;
            }
            set
            {
                this.k_25Field = value;
            }
        }

        public decimal K_26
        {
            get
            {
                return this.k_26Field;
            }
            set
            {
                this.k_26Field = value;
            }
        }

        public decimal K_27
        {
            get
            {
                return this.k_27Field;
            }
            set
            {
                this.k_27Field = value;
            }
        }

        public decimal K_28
        {
            get
            {
                return this.k_28Field;
            }
            set
            {
                this.k_28Field = value;
            }
        }

        public decimal K_29
        {
            get
            {
                return this.k_29Field;
            }
            set
            {
                this.k_29Field = value;
            }
        }

        public decimal K_30
        {
            get
            {
                return this.k_30Field;
            }
            set
            {
                this.k_30Field = value;
            }
        }

        public decimal K_31
        {
            get
            {
                return this.k_31Field;
            }
            set
            {
                this.k_31Field = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool K_31Specified
        {
            get
            {
                return this.k_31FieldSpecified;
            }
            set
            {
                this.k_31FieldSpecified = value;
            }
        }

        public decimal K_32
        {
            get
            {
                return this.k_32Field;
            }
            set
            {
                this.k_32Field = value;
            }
        }

        public decimal K_33
        {
            get
            {
                return this.k_33Field;
            }
            set
            {
                this.k_33Field = value;
            }
        }

        public decimal K_34
        {
            get
            {
                return this.k_34Field;
            }
            set
            {
                this.k_34Field = value;
            }
        }

        public decimal K_35
        {
            get
            {
                return this.k_35Field;
            }
            set
            {
                this.k_35Field = value;
            }
        }

        public decimal K_36
        {
            get
            {
                return this.k_36Field;
            }
            set
            {
                this.k_36Field = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool K_36Specified
        {
            get
            {
                return this.k_36FieldSpecified;
            }
            set
            {
                this.k_36FieldSpecified = value;
            }
        }

        public decimal K_37
        {
            get
            {
                return this.k_37Field;
            }
            set
            {
                this.k_37Field = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool K_37Specified
        {
            get
            {
                return this.k_37FieldSpecified;
            }
            set
            {
                this.k_37FieldSpecified = value;
            }
        }

        public decimal K_38
        {
            get
            {
                return this.k_38Field;
            }
            set
            {
                this.k_38Field = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool K_38Specified
        {
            get
            {
                return this.k_38FieldSpecified;
            }
            set
            {
                this.k_38FieldSpecified = value;
            }
        }

        public decimal K_39
        {
            get
            {
                return this.k_39Field;
            }
            set
            {
                this.k_39Field = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool K_39Specified
        {
            get
            {
                return this.k_39FieldSpecified;
            }
            set
            {
                this.k_39FieldSpecified = value;
            }
        }
    }

    public partial class JPKSprzedazCtrl
    {

        private string liczbaWierszySprzedazyField;

        private decimal podatekNaleznyField;

        public string LiczbaWierszySprzedazy
        {
            get
            {
                return this.liczbaWierszySprzedazyField;
            }
            set
            {
                this.liczbaWierszySprzedazyField = value;
            }
        }

        public decimal PodatekNalezny
        {
            get
            {
                return this.podatekNaleznyField;
            }
            set
            {
                this.podatekNaleznyField = value;
            }
        }
    }

    public partial class JPKZakupWiersz
    {

        private string lpZakupuField;

        private string nrDostawcyField;

        private string nazwaDostawcyField;

        private string adresDostawcyField;

        private string dowodZakupuField;

        private System.DateTime dataZakupuField;

        private System.DateTime dataWplywuField;

        private bool dataWplywuFieldSpecified;

        private decimal k_43Field;

        private decimal k_44Field;

        private decimal k_45Field;

        private decimal k_46Field;

        private decimal k_47Field;

        private bool k_47FieldSpecified;

        private decimal k_48Field;

        private bool k_48FieldSpecified;

        private decimal k_49Field;

        private bool k_49FieldSpecified;

        private decimal k_50Field;

        private bool k_50FieldSpecified;

        public string LpZakupu
        {
            get
            {
                return this.lpZakupuField;
            }
            set
            {
                this.lpZakupuField = value;
            }
        }

        public string NrDostawcy
        {
            get
            {
                return this.nrDostawcyField;
            }
            set
            {
                this.nrDostawcyField = value;
            }
        }

        public string NazwaDostawcy
        {
            get
            {
                return this.nazwaDostawcyField;
            }
            set
            {
                this.nazwaDostawcyField = value;
            }
        }

        public string AdresDostawcy
        {
            get
            {
                return this.adresDostawcyField;
            }
            set
            {
                this.adresDostawcyField = value;
            }
        }

        public string DowodZakupu
        {
            get
            {
                return this.dowodZakupuField;
            }
            set
            {
                this.dowodZakupuField = value;
            }
        }

        public System.DateTime DataZakupu
        {
            get
            {
                return this.dataZakupuField;
            }
            set
            {
                this.dataZakupuField = value;
            }
        }

        public System.DateTime DataWplywu
        {
            get
            {
                return this.dataWplywuField;
            }
            set
            {
                this.dataWplywuField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataWplywuSpecified
        {
            get
            {
                return this.dataWplywuFieldSpecified;
            }
            set
            {
                this.dataWplywuFieldSpecified = value;
            }
        }

        public decimal K_43
        {
            get
            {
                return this.k_43Field;
            }
            set
            {
                this.k_43Field = value;
            }
        }

        public decimal K_44
        {
            get
            {
                return this.k_44Field;
            }
            set
            {
                this.k_44Field = value;
            }
        }

        public decimal K_45
        {
            get
            {
                return this.k_45Field;
            }
            set
            {
                this.k_45Field = value;
            }
        }

        public decimal K_46
        {
            get
            {
                return this.k_46Field;
            }
            set
            {
                this.k_46Field = value;
            }
        }

        public decimal K_47
        {
            get
            {
                return this.k_47Field;
            }
            set
            {
                this.k_47Field = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool K_47Specified
        {
            get
            {
                return this.k_47FieldSpecified;
            }
            set
            {
                this.k_47FieldSpecified = value;
            }
        }

        public decimal K_48
        {
            get
            {
                return this.k_48Field;
            }
            set
            {
                this.k_48Field = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool K_48Specified
        {
            get
            {
                return this.k_48FieldSpecified;
            }
            set
            {
                this.k_48FieldSpecified = value;
            }
        }

        public decimal K_49
        {
            get
            {
                return this.k_49Field;
            }
            set
            {
                this.k_49Field = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool K_49Specified
        {
            get
            {
                return this.k_49FieldSpecified;
            }
            set
            {
                this.k_49FieldSpecified = value;
            }
        }

        public decimal K_50
        {
            get
            {
                return this.k_50Field;
            }
            set
            {
                this.k_50Field = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool K_50Specified
        {
            get
            {
                return this.k_50FieldSpecified;
            }
            set
            {
                this.k_50FieldSpecified = value;
            }
        }
    }

    public partial class JPKZakupCtrl
    {

        private string liczbaWierszyZakupowField;

        private decimal podatekNaliczonyField;

        public string LiczbaWierszyZakupow
        {
            get
            {
                return this.liczbaWierszyZakupowField;
            }
            set
            {
                this.liczbaWierszyZakupowField = value;
            }
        }

        public decimal PodatekNaliczony
        {
            get
            {
                return this.podatekNaliczonyField;
            }
            set
            {
                this.podatekNaliczonyField = value;
            }
        }
    }
}
